/* The shirt room. Historical identity + explicitly interpretive original garment studies.
   Keep the five original IDs and favorite storage key stable. No external requests. */
(()=>{'use strict';
const sources={
 launch26:'https://www.ussoccer.com/stories/2026/03/nike-unveils-new-national-team-stars-stripes-jerseys-kits-fifa-world-cup',
 denim:'https://www.ussoccer.com/stories/2026/05/usmnt/26-moments-usa-breaks-through-1994-fifa-world-cup-home-soil',
 launch24:'https://www.ussoccer.com/2024-jersey',timeline:'https://www.ussoccer.com/history/timeline'
};
/* Each record separates the source-backed identity from our visual reading. */
const collection=[
 {id:'denim',year:1994,edition:'Away',maker:'adidas',label:'Denim',name:'The denim one.',family:'stars',base:'#668ab3',accent:'#ecf0f0',trim:'#b6223d',pattern:'denim',collar:'v',source:sources.denim,
 fact:'The denim away shirt belongs to the 1994 World Cup on home soil. U.S. Soccer’s retrospective remembers it as part of the team’s breakthrough into American public life.',
 reading:'Everyday American clothing, on the world stage. The big stars feel almost unruly against the denim-like field. That friction is the whole idea.',
 patternNote:'Large, scattered stars interrupt a soft blue field. Compare with 2026 Stars: the motif survives, but its contrast changes completely.',collarNote:'This study gives the star field a red frame at the neckline. The seams and fabric shading are illustrative, not a technical garment specification.'},
 {id:'sash',year:2010,edition:'Home',maker:'Nike',label:'White sash',name:'One diagonal.',family:'sash',base:'#f1f1ed',accent:'#b7bdc3',trim:'#253347',pattern:'sash',collar:'round',source:sources.timeline,
 fact:'This collection associates the white 2010 shirt with the Donovan-versus-Algeria memory. The linked federation timeline supplies the football context.',
 reading:'A quiet shirt with one decisive line. The diagonal moves the eye across the body; everything around it gets out of the way.',patternNote:'Follow the sash from shoulder to waist. Its direction matters more than ornament. Our illustration simplifies its tone and proportions.',collarNote:'The unobtrusive neckline lets the diagonal remain the main event. This is a visual interpretation; the timeline does not document manufacturing details.'},
 {id:'bomb',year:2014,edition:'Away',maker:'Nike',label:'Bomb Pop',name:'Summer in blocks.',family:'blocks',base:'#d52e45',accent:'#3176b5',trim:'#27558c',pattern:'bomb',collar:'round',source:sources.launch24,
 fact:'U.S. Soccer’s 2024 collection names the 2014 away shirt as one of its design references. In Gordon’s words: “The shirt was beautiful.”',
 reading:'Blue, white, red. The popsicle nickname makes sense before anyone explains it. Large uninterrupted bands give the shirt its personality.',patternNote:'Three large color fields make the design readable at a distance. Compare the 2024 away study to see the same palette become more restless.',collarNote:'The blue neckline sits inside the blue upper field. In this study that continuity keeps attention on the three horizontal bands.'},
 {id:'classic24',year:2024,edition:'Home',maker:'Nike',label:'American Classic',name:'The edge does the work.',family:'minimal',base:'#eeeee9',accent:'#c9283d',trim:'#172d4b',pattern:'classic24',collar:'rib',source:sources.launch24,
 fact:'The 2024 American Classic pairs a white shirt with red, white and blue rib details at the two-piece collar and cuffs.',
 reading:'White space is an active design choice. Small, concentrated color at the openings makes the shirt feel finished without covering its whole surface.',patternNote:'Move your eye from the open white body to the cuff. Here, the trim carries the identity rather than a central pattern.',collarNote:'U.S. Soccer explicitly calls out the two-piece collar and graphic rib. The study enlarges their color contrast; the stitching is interpretive.'},
 {id:'icon24',year:2024,edition:'Away',maker:'Nike',label:'American Icon',name:'The flag, remixed.',family:'abstract',base:'#2461a1',accent:'#ca3043',trim:'#193b68',pattern:'icon24',collar:'round',source:sources.launch24,
 fact:'The 2024 American Icon uses a distorted red, white and blue design. The federation identifies both the historic sash and the 2014 away shirt as references.',
 reading:'The palette stays familiar while the boundaries become unstable. Compared with Bomb Pop, the color transition does more of the talking.',patternNote:'A distorted transition can suggest motion without adding more colors. The wave and fade in this original study are illustrative, not an exact print map.',collarNote:'The dark neckline recedes into the upper color field. Compare with the home shirt, where the collar becomes the point of emphasis.'},
 {id:'stripes',year:2026,edition:'Stripes',maker:'Nike',label:'Stripes',name:'Loud and proud.',family:'stripes',base:'#f2f0e8',accent:'#c82b43',trim:'#152b42',pattern:'stripes26',collar:'round',source:sources.launch26,
 fact:'The light half of the 2026 collection was developed with player feedback. The official launch also introduced an “Inner Pride” mark inside the collar.',
 reading:'An unmistakable flag starting point, with a rhythm that refuses to sit perfectly still. Follow the red across the body rather than reading each stripe alone.',patternNote:'The flowing stripes give this study a different rhythm from straight hoops. This is our reading of the design, not a claim about how the shirt performs.',collarNote:'The official “Inner Pride” mark sits inside the collar. Our cutaway indicates its location; it does not reproduce the actual mark.'},
 {id:'stars',year:2026,edition:'Stars',maker:'Nike',label:'Stars',name:'The quiet stars.',family:'stars',base:'#132439',accent:'#2b4159',trim:'#101f32',pattern:'stars26',collar:'round',source:sources.launch26,
 fact:'The dark half of the 2026 collection was described at launch as a design that also works away from the field. The new collection has bespoke Stars and Stripes lettering.',
 reading:'Low contrast makes the stars feel discovered rather than announced. Gordon’s own navy number 4, below, makes the off-field connection personal.',patternNote:'Compare with 1994 Denim. A star can be the loudest thing on a shirt or something you notice only when you look closer.',collarNote:'The neckline stays within the dark palette. Official marks and lettering are omitted from this original study; use the source link to see the real product.'}
];
// Historical names checked against federation Brackitology; visual archive links are identified separately.
const bracket='https://www.ussoccer.com/stories/2020/04/2019-wnt-home-4-star-kit-wins-us-soccer-brackitology-fan-vote';
collection.push(
 {id:'stripes94',year:1994,edition:'Home',maker:'adidas',label:'Waving stripes',name:'The other ’94.',family:'stripes',base:'#f0efe8',accent:'#b62a3c',trim:'#193149',pattern:'vertical94',collar:'v',source:'https://www.footballkitarchive.com/usa-1994-home-kit-8749/',sourceLabel:'Historical visual archive',
 fact:'The 1994 home design uses wavy vertical red-and-white stripes, white sleeves and a navy V-neck with red trim. The visual reference here is a kit archive, rather than a federation launch page.',
 reading:'Denim tends to take the whole conversation. Put its partner beside it: the stripes are vertical, but their waviness keeps them from feeling rigid.',patternNote:'Follow a red stripe from shoulder to hem. Unlike a straight pinstripe, its changing width and direction make the field feel unsettled.',collarNote:'A dark V-neck creates a stopping point above the moving stripes. The roomy sleeves in this study evoke the period; exact tailoring is not reproduced.'},
 {id:'home02',year:2002,edition:'Home',maker:'Nike',label:'Side-panel white',name:'Identity at the edges.',family:'blocks',base:'#efeee9',accent:'#193955',trim:'#e4e3dd',pattern:'sidepanels',collar:'v',source:bracket,visualSource:'https://www.footballkitarchive.com/usa-2002-home-kit-9788/',
 fact:'The 2002 home shirt pairs a white body with angled red-and-navy side panels and red detail at the neckline and cuffs. Its identity is included in U.S. Soccer’s historical kit bracket.',
 reading:'The center stays open. Instead of a large chest graphic, the geometry frames the body from its edges—a very different kind of confidence.',patternNote:'The panel is a border and a directional line at once. Compare with 2024 Home: both leave white space in charge, but place their color differently.',collarNote:'The neckline insert and cuff details echo the side-panel palette. This original study simplifies their exact construction.'},
 {id:'home06',year:2006,edition:'Home',maker:'Nike',label:'Offset band',name:'Off center. On purpose.',family:'stripes',base:'#eeeee8',accent:'#c5283e',trim:'#172e49',pattern:'band06',collar:'v',source:bracket,visualSource:'https://www.footballkitarchive.com/usa-2006-home-kit-9768/',
 fact:'The 2006 home design has an offset vertical band in red and navy, with gold edging at the cuffs. This is an illustration of that graphic arrangement, not an exact replica.',
 reading:'Move the stripe off the middle and the whole shirt changes. The open white field becomes something the band can push against.',patternNote:'Compare with a diagonal sash. Both create a single strong line; the vertical band feels anchored while the diagonal suggests movement.',collarNote:'Small cuff accents sit far away from the main band. Our study keeps the gold restrained so it does not become the primary color.'},
 {id:'dtom06',year:2006,edition:'Special',maker:'Nike',label:'Don’t Tread',name:'The red exception.',family:'sash',base:'#b71d35',accent:'#f0eee4',trim:'#182d44',pattern:'sash',sashBorder:'#182d44',collar:'polo',collarFill:'#b71d35',collarEdge:'#182d44',source:bracket,visualSource:'https://www.footballkitarchive.com/usa-2006-special-kit-9794/',
 fact:'The “Don’t Tread” special shirt belongs to 2006, rather than the uncertain 2010 recollection in the earlier page. Its red body carries a white diagonal sash bordered with navy.',
 reading:'Reverse the expected balance: red becomes the field rather than an accent. The sash keeps a familiar vocabulary while the mood changes.',patternNote:'The dark border gives a light sash extra separation from red. Set it beside the 2010 white or navy study to see what the base color does.',collarNote:'The red foldover polo collar has navy edging. Our close-up preserves that distinction from the 2010 crew neck; the special shirt’s marks and insignia remain omitted.'},
 {id:'home08',year:2008,edition:'Home',maker:'Nike',label:'Quiet hoops',name:'A whisper of stripes.',family:'stripes',base:'#ecece7',accent:'#d0d1ce',trim:'#eeeae1',pattern:'hoops',collar:'round',source:bracket,visualSource:'https://www.si.com/soccer/2015/04/22/us-mens-national-team-soccer-uniforms',visualLabel:'Sports Illustrated visual history',
 fact:'The 2008 home shirt uses subtle white-and-gray hoops with restrained red detail. U.S. Soccer’s historical fan bracket includes the 2008 Home identity.',
 reading:'A stripe does not have to shout. With so little contrast, the pattern behaves more like texture than a declaration.',patternNote:'Compare with 2012 Waldo. Repeating horizontal bands can feel quiet or unmistakable depending on their contrast—not simply their existence.',collarNote:'The light neckline stays close to the body color. This study focuses on the quiet hoops rather than reconstructing every trim detail.'},
 {id:'away10',year:2010,edition:'Away',maker:'Nike',label:'Navy sash',name:'The diagonal, reversed.',family:'sash',base:'#152d45',accent:'#f3f1e9',trim:'#b22b3e',pattern:'sash',collar:'round',source:bracket,
 fact:'The 2010 away shirt carries a white sash over an obsidian-blue body. U.S. Soccer includes the 2010 Away in its historical kit bracket.',
 reading:'Same strong diagonal, reversed contrast. The light line reads immediately against navy; in the home study it sits much closer to the white field.',patternNote:'Put both 2010 shirts side by side. A shared motif can connect two designs even when their visual weight feels completely different.',collarNote:'A restrained neckline keeps the diagonal in charge. The illustration does not reproduce official logos or manufacturing details.'},
 {id:'waldo12',year:2012,edition:'Home',maker:'Nike',label:'Waldo',name:'No hiding in these hoops.',family:'stripes',base:'#f0efe7',accent:'#c42c43',trim:'#172c46',pattern:'hoops',collar:'round',source:bracket,
 fact:'The 2012 red-and-white hoop shirt is identified as “Waldo” in U.S. Soccer’s historical kit bracket. This study preserves the broad stripes and navy neckline.',
 reading:'Repetition becomes identity. It is a flag-like rhythm you can recognize across a room, without needing to read a badge.',patternNote:'Straight hoops versus flowing 2026 stripes: the family resemblance is clear, but the rhythm changes. Decide which feels more like a lasting uniform.',collarNote:'The navy opening punctuates the red-and-white rhythm. Blank chest space here is deliberate: official crest and maker marks are omitted.'},
 {id:'centennial13',year:2013,edition:'Centennial',maker:'Nike',label:'Centennial',name:'A century, stripped back.',family:'minimal',base:'#f1f0e9',accent:'#152d47',trim:'#152d47',pattern:'centennial',collar:'v',source:bracket,visualSource:'https://www.mlssoccer.com/news/us-national-team-joins-jersey-week-craze-new-centennial-kits',visualLabel:'MLS · contemporary launch report',
 fact:'The centennial shirt combines a white body, a deep navy V-neck and navy cuffs. Its vintage shield is omitted from the drawing; the original shield’s stars are not men’s World Cup trophy stars.',
 reading:'When the palette is this restrained, the neckline becomes the signature. The empty field gives every remaining detail more responsibility.',patternNote:'Compare with a pattern-heavy shirt. A lack of printed pattern is still a decision about where the eye should land.',collarNote:'The navy V-neck makes a sharp boundary against white. This study emphasizes that geometry rather than reproducing the historical shield.'},
 {id:'polo14',year:2014,edition:'Home',maker:'Nike',label:'White polo',name:'A different kind of collar.',family:'minimal',base:'#eeeee9',accent:'#bf253c',trim:'#e9e8e1',pattern:'polo14',collar:'polo',source:'https://www.si.com/soccer/2014/03/03/usmnt-uswnt-us-soccer-new-jersey-world-cup',sourceLabel:'Contemporary launch report',
 fact:'The 2014 home shirt uses a white polo collar with red edging and fine gray pinstripes. The linked contemporary report supplies the visual reference.',
 reading:'Put this beside Bomb Pop from the same year. One leans on the familiar language of a polo; the other makes big color blocks do the work.',patternNote:'The pinstripes are deliberately faint. They add a layer at close range without competing with the collar from a distance.',collarNote:'Folded points, a short opening and red edging make the neckline the main design feature. Our pattern and stitching remain simplified.'}
);
collection.push(
 {id:'away15',year:2015,edition:'Away',maker:'Nike',label:'Blue gradient',name:'From white to midnight.',family:'abstract',base:'#245082',accent:'#143050',trim:'#e9e9e3',pattern:'gradient15',collar:'v',source:'https://www.ussoccer.com/mnt-travel-roster/2015/02/us-mnt-and-wnt-2015-nike-away-kit-debuts-this-march',
 fact:'The 2015 away design graduates from light shoulders through blue toward a dark hem. Directional rays, a slim V-neck and a red insert add structure to the fade.',
 reading:'Instead of dividing the shirt into separate blocks, the color travels. The eye reads it as a descent from light to dark.',patternNote:'Compare with Bomb Pop: both use large color areas, but one separates them while the other joins them. The rays give the gradient a direction.',collarNote:'A small red insert interrupts the blue-and-white palette. The study simplifies the neckline and ray placement rather than recreating the manufactured print.'},
 {id:'away16',year:2016,edition:'Away',maker:'Nike',label:'Black / split sleeves',name:'A black canvas.',family:'blocks',base:'#202125',accent:'#bd263d',trim:'#181b22',pattern:'black16',collar:'v',source:'https://www.soccerbible.com/performance/football-apparel/2016/03/nike-2016-usa-national-soccer-kits/',sourceLabel:'Contemporary kit report',
 fact:'The 2016 away design uses a black torso with the wearer’s right sleeve red and left sleeve blue. In a front view, red therefore appears on the viewer’s left.',
 reading:'The colors frame the body instead of covering it. Black becomes the pause between two unequal-color sleeves.',patternNote:'This is deliberate asymmetry, not a red-and-blue gradient. The sleeves keep their separate roles in this illustration.',collarNote:'A dark neckline stays within the black field. Compared with a light shirt’s contrasting collar, it creates less of a visual stopping point.'},
 {id:'goldcup17',year:2017,edition:'Gold Cup special',maker:'Nike',label:'Gold Cup hoops',name:'Dark stars. Bold hoops.',family:'stripes',base:'#17344f',accent:'#b9263f',trim:'#142d46',pattern:'goldcup17',collar:'round',source:'https://www.ussoccer.com/stories/2017/07/us-soccer-unveils-us-mnt-2017-gold-cup-kit',
 fact:'The 2017 Gold Cup special combines red-and-navy hoops with tonal dark stars and rows of white stars on the sleeves. It is a specific Gold Cup design, not a “2018 World Cup shirt.”',
 reading:'This shirt stacks two identity cues: stripes first, then stars. Compare with Waldo, where the broad red-and-white repetition is already enough.',patternNote:'Notice the difference between tonal stars on the body and white stars on the sleeves. The illustration abstracts their scale and exact placement.',collarNote:'The dark opening continues the navy palette. The sleeve-star rows, rather than the collar, provide the bright punctuation.'},
 {id:'home18',year:2018,edition:'Home',maker:'Nike',label:'Broken bars',name:'Stripes, interrupted.',family:'stripes',base:'#eeeee9',accent:'#c32c43',trim:'#15344e',pattern:'home18',collar:'round',source:'https://www.ussoccer.com/stories/2018/03/distinctive-new-kit-launches-us-soccers-next-generation',
 fact:'The 2018 home design breaks red-to-blue horizontal bars into a diagonal flow across a white body. It was introduced as part of U.S. Soccer’s next-generation kit launch.',
 reading:'A familiar stripe becomes less predictable when its continuity breaks. White space cuts into the color and becomes part of the pattern.',patternNote:'Compare with the straight bands of Waldo. Here the gaps and diagonal displacement create movement, not a change in the basic national palette.',collarNote:'The simple neckline leaves the interrupted bars in charge. The print geometry in this study is an interpretation, not an exact repeat.'},
 {id:'away18',year:2018,edition:'Away',maker:'Nike',label:'Blue geometry',name:'The shape of absence.',family:'abstract',base:'#154c7b',accent:'#102f51',trim:'#163a61',pattern:'away18',collar:'round',source:'https://www.ussoccer.com/stories/2018/03/distinctive-new-kit-launches-us-soccers-next-generation',
 fact:'The 2018 away shirt works in deep blue, using negative-space stripe geometry. It is the dark counterpart to that year’s broken-bar home design.',
 reading:'What looks like a printed stripe can also be the space left between shapes. Close contrast makes you inspect the pattern instead of recognizing it instantly.',patternNote:'Look at the blue gaps between dark forms. In this study the negative space is doing as much work as the filled geometry.',collarNote:'A blue neckline reinforces the restricted palette. The seam lines are illustrative and do not claim exact construction.'},
 {id:'home20',year:2020,edition:'Home',maker:'Nike',label:'Clean white',name:'The quiet center.',family:'minimal',base:'#f0f0eb',accent:'#be263e',trim:'#f0f0eb',pattern:'home20',collar:'round',source:'https://www.ussoccer.com/stories/2020/02/new-uswnt-usmnt-jersey-released-nike-soccer-uniforms-home-away',
 fact:'The 2020 home design keeps the body white and concentrates red-and-blue detail at the cuffs and sides. The official launch pairs it with the States away shirt.',
 reading:'A large empty field can make small accents feel deliberate. Put this beside the busy States study to see how far one collection can stretch.',patternNote:'The main field is quiet; the edge carries the signal. Compare with 2002 Home and 2024 Home for three different ways to frame white space.',collarNote:'The light neckline does not compete with the cuff colors. This study abstracts the seam and side-trim construction.'},
 {id:'states20',year:2020,edition:'Away',maker:'Nike',label:'States',name:'A country in contours.',family:'abstract',base:'#163c64',accent:'#286299',trim:'#143252',pattern:'states20',collar:'round',source:'https://www.ussoccer.com/stories/2020/02/new-uswnt-usmnt-jersey-released-nike-soccer-uniforms-home-away',
 fact:'The States away design uses irregular, hand-drawn state-border contours. Its visual idea is distinct from the fluid dye treatment on the 2022 away shirt.',
 reading:'A map becomes a field of marks rather than a diagram to navigate. The irregular line gives the navy-and-blue surface its own rhythm.',patternNote:'These original contour lines interpret the idea; they are not a geographic map or the manufacturer’s actual print. The important distinction is contour, not pixel camouflage.',collarNote:'The dark collar gives the busy field an edge. Compare with a blank white shirt to see how surface activity changes the role of trim.'},
 {id:'dazzle21',year:2021,edition:'Away',maker:'Nike',label:'Dazzle',name:'Break the outline.',family:'abstract',base:'#d53148',accent:'#182e49',trim:'#142a41',pattern:'dazzle',collar:'v',source:'https://www.footyheadlines.com/2021/02/usa-2021-away-kit-leaked-first-look-at.html',sourceLabel:'Historical kit visual reference',
 fact:'The 2021 away design uses hard-edged red-and-navy diagonal zigzags with unequal spacing. The drawing is based on the linked visual archive.',
 reading:'There is no gentle transition here. The eye keeps changing direction as it meets another sharp edge.',patternNote:'Compare with the 2022 dye study: one breaks the surface with angles, the other with fluid shapes. Both are busy; they are busy in different ways.',collarNote:'A dark V-neck gives the surrounding angular pattern a fixed point. Exact edge alignment and insignia are intentionally not reconstructed.'},
 {id:'home22',year:2022,edition:'Home',maker:'Nike',label:'White / sleeve bands',name:'The shoulders speak.',family:'minimal',base:'#f2f2ee',accent:'#19334e',trim:'#f0f0e9',pattern:'shoulders22',collar:'round',source:'https://www.ussoccer.com/stories/2022/09/us-soccer-and-nike-launch-2022-uniform-collection-for-men-and-womens-national-team',
 fact:'The 2022 home design combines a white body with broad navy-and-red sleeve details and a centered crest. The crest is deliberately omitted from our graphic study.',
 reading:'White carries the body, but the upper silhouette does most of the signaling. Compare with 2024 Home, which puts a finer line of color at the openings.',patternNote:'The sleeve treatment frames a quiet center. Our study focuses on that balance without substituting a fictional badge for the actual centered crest.',collarNote:'The light collar leaves the colored sleeve areas in charge. The exact cut and stitching are simplified.'},
 {id:'away22',year:2022,edition:'Away',maker:'Nike',label:'Blue ice dye',name:'Let the color run.',family:'abstract',base:'#2a68b2',accent:'#152d48',trim:'#13263b',pattern:'tiedye',collar:'round',source:'https://www.ussoccer.com/stories/2022/09/us-soccer-and-nike-launch-2022-uniform-collection-for-men-and-womens-national-team',
 fact:'The 2022 away design uses a blue-and-black ice-dye treatment. It should not be confused with the 2020 States shirt’s hand-drawn contour pattern.',
 reading:'Fluid, uneven patches make the surface feel less controlled than a striped shirt. The pattern has energy without a single organizing line.',patternNote:'The dye shapes here are original approximations, not a copy of a particular retail shirt. Compare with Dazzle’s sharp diagonals.',collarNote:'A dark neckline gives the fluid pattern one steady boundary. No actual material behavior or dye process is simulated.'},
 {id:'away23',year:2023,edition:'Away',maker:'Nike',label:'Star-point blue',name:'Stars at the edges.',family:'stars',base:'#224b91',accent:'#c22d42',trim:'#ba2b40',pattern:'away23',collar:'round',source:'https://store.ussoccer.com/products/usasmz2211-mens-nike-usmnt-2023-away-stadium-jersey',sourceLabel:'U.S. Soccer · official product reference',
 fact:'The 2023 away design is blue, with red star-point details around the collar and sleeves. This is a men’s USMNT product reference, distinct from the women’s white 2023 home design.',
 reading:'Instead of scattering complete stars across the body, this study lets points emerge at the edges. A national motif can be present without being literal everywhere.',patternNote:'The red points work as fragments. Compare with 1994 Denim: complete stars and cropped star shapes create very different kinds of emphasis.',collarNote:'The red detail makes the neck opening a focal point. Our simplified geometry does not reproduce the precise product pattern.'},
 {id:'heartbeat25',year:2025,edition:'Away',maker:'Nike',label:'Heartbeat',name:'A pulse in navy.',family:'stripes',base:'#132640',accent:'#243c5c',trim:'#162d48',pattern:'heartbeat25',collar:'round',source:'https://www.ussoccer.com/stories/2025/05/us-soccer-unveils-2025-national-team-kits-fusion-heritage-fashion-uswnt-usmnt',visualSource:'https://store.ussoccer.com/products/usasmz2501-mens-nike-usmnt-2025-heartbeat-away-match-jersey',visualLabel:'U.S. Soccer · men’s Heartbeat product',
 fact:'The Heartbeat away design uses deep navy vertical stripes with red-and-blue accents. The men wore Heartbeat and the 2024 white design; the 2025 Brilliant home design was for the USWNT.',
 reading:'A vertical rhythm can feel like a pulse even in a restrained palette. This is the darker, closer-looking end of the stripe family.',patternNote:'These are vertical stripes, unlike the horizontal hoops elsewhere in the collection. Compare with 2006’s isolated vertical band: repetition changes the effect.',collarNote:'The collar stays in the navy family while accents interrupt the surface. This study deliberately omits official fonts, logos and trophy stars.'}
);

collection.sort((a,b)=>a.year-b.year);

const kitMap=Object.fromEntries(collection.map(k=>[k.id,k]));
const $=id=>document.getElementById(id), root=$('collection');if(!root)return;
const familyLabels={stars:'Stars',stripes:'Stripes & hoops',sash:'Sashes',blocks:'Color blocks',minimal:'Minimal',abstract:'Abstract'};
const key='usa26-kit-room-favorite-v1';let favorite=null,storageOK=true,current='denim',detail='whole',compareA='denim',compareB='stars',svgSerial=0;
try{const value=localStorage.getItem(key);if(kitMap[value])favorite=value}catch{storageOK=false}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shirtShape='M127 62 L170 43 Q210 65 250 43 L293 62 Q324 90 365 142 L309 181 L285 151 L293 388 Q210 403 127 388 L135 151 L111 181 L55 142 Q96 90 127 62 Z';
function star(x,y,r=24,stretch=1){let points=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rad=i%2?r*.43:r;points.push(`${(x+Math.cos(a)*rad*stretch).toFixed(1)},${(y+Math.sin(a)*rad).toFixed(1)}`)}return `<polygon points="${points.join(' ')}"/>`;}
function pattern(k,id){const c=k.accent;switch(k.pattern){
 case 'denim':return `<g fill="${c}">${star(112,116,32,1.2)}${star(225,100,31,1.25)}${star(308,145,33,1.15)}${star(163,215,35,1.2)}${star(248,265,33,1.2)}${star(143,331,36,1.25)}${star(298,378,36,1.3)}</g>`;
 case 'stars26':return `<g fill="${c}">${star(123,116,52)}${star(259,143,66)}${star(163,296,65)}${star(316,355,56)}</g>`;
 case 'sash':return `<path d="M94 33L144 26L317 388L267 410Z" fill="${c}" ${k.sashBorder?'stroke="'+k.sashBorder+'" stroke-width="9"':''}/>`;
 case 'bomb':return '<path d="M0 0H420V128H0Z" fill="#3176b5"/><path d="M0 128H420V188H0Z" fill="#f5f2e9"/>';
 case 'stripes26':{let out='';for(let y=95;y<430;y+=73)out+=`<path d="M20 ${y}Q118 ${y-32} 210 ${y}T400 ${y}V${y+34}Q304 ${y+64} 210 ${y+34}T20 ${y+34}Z" fill="${c}"/>`;return out;}
 case 'hoops':{let out='';for(let y=99;y<430;y+=61)out+=`<path d="M0 ${y}H420V${y+30}H0Z" fill="${c}"/>`;return out+(k.id==='home08'?'<path d="M40 132L111 175M380 132L309 175" stroke="#ba2c40" stroke-width="2"/>':'');}
 case 'vertical94':{let out='';for(let x=85;x<380;x+=68)out+=`<path d="M${x} 10Q${x-18} 160 ${x+12} 410H${x+46}Q${x+14} 180 ${x+33} 10Z" fill="${c}"/>`;return out+`<path d="M119 63L151 54L130 153L108 190L44 150ZM301 63L269 54L290 153L312 190L376 150Z" fill="${k.base}"/>`;}
 case 'classic24':return '<path d="M37 127L111 173M383 127L309 173" stroke="#172d4b" stroke-width="18"/><path d="M37 127L111 173M383 127L309 173" stroke="#c9283d" stroke-width="7"/>';
 case 'icon24':return `<defs><linearGradient id="${id}-blur" x1="0" y1="0" x2=".2" y2="1"><stop offset=".3" stop-color="#2867b0"/><stop offset=".5" stop-color="#edede6"/><stop offset=".64" stop-color="#d5394d"/></linearGradient></defs><path d="M0 0H420V430H0Z" fill="url(#${id}-blur)"/><path d="M0 215Q110 150 220 202T420 160" stroke="#eee9df" stroke-width="12" fill="none" opacity=".55"/>`;
 case 'gradient15':return `<defs><linearGradient id="${id}-blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#e9eff0"/><stop offset=".26" stop-color="#93bddb"/><stop offset=".55" stop-color="#3167a0"/><stop offset="1" stop-color="#152d49"/></linearGradient></defs><path d="M0 0H420V430H0Z" fill="url(#${id}-blue)"/><g fill="#173e65" opacity=".14"><path d="M210 90L98 400L20 430ZM210 90L172 430L213 430ZM210 90L290 430L378 430Z"/></g><path d="M137 143L123 390M283 143L297 390" stroke="#e7edf0" stroke-width="10"/><path d="M199 64L210 80L221 64Z" fill="#bc263d"/>`;
 case 'goldcup17':{let out='';for(let y=90;y<430;y+=60)out+=`<path d="M0 ${y}H420V${y+30}H0Z" fill="#b42a40"/>`;return out+`<g fill="#101f39" opacity=".6">${star(170,210,44)}${star(245,285,48)}</g><g fill="#efeee6">${star(91,136,8)}${star(104,149,8)}${star(329,136,8)}${star(316,149,8)}</g>`;}
 case 'home18':{let out='';for(let n=0;n<9;n++){let y=87+n*35;out+=`<path d="M40 ${y}H${177+n*4}L${200+n*4} ${y+17}H380V${y+29}H${203+n*4}L${180+n*4} ${y+12}H40Z" fill="${n<4?'#ba2d44':'#245d92'}"/>`;}return out;}
 case 'away18':return '<path d="M10 80L152 80L209 124L350 124V152H195L140 109H10ZM35 210H174L229 249H410V279H215L160 239H35ZM-20 344H140L195 381H405V411H181L126 374H-20Z" fill="#102f51"/>';
 case 'home20':return '<path d="M37 128L111 176" stroke="#bf263e" stroke-width="13"/><path d="M383 128L309 176" stroke="#204f85" stroke-width="13"/><path d="M131 186V388" stroke="#bf263e" stroke-width="9"/><path d="M289 186V388" stroke="#204f85" stroke-width="9"/>';
 case 'states20':return `<g fill="none" stroke="${c}" stroke-width="5" stroke-linejoin="round"><path d="M72 88L131 98L140 135L188 130L197 177L161 204L171 239L134 267L142 312L107 347"/><path d="M180 46L187 104L225 115L244 82L283 96L279 148L313 177L292 217L322 251"/><path d="M165 205L213 212L233 193L267 217L254 270L294 280L278 318L242 308L235 357L190 347L173 395"/><path d="M127 313L169 298L185 270L217 282L209 326L192 347M188 130L224 157L233 193M279 148L253 165L224 157M72 147L115 159L131 194L161 204M278 318L304 342M235 357L264 397"/></g>`;
 case 'away23':return '<path d="M82 134L96 131L104 152L121 154L111 177L98 159L80 163ZM338 134L324 131L316 152L299 154L309 177L322 159L340 163ZM170 45L176 77L193 69L210 93L225 70L244 76L250 45L211 57Z" fill="#bb2c42"/>';
 case 'heartbeat25':{let out='';for(let x=118;x<320;x+=30)out+=`<path d="M${x} 40V430" stroke="#2a4261" stroke-width="13"/>`;return out+'<path d="M133 87L161 93M240 80L272 85M145 276L174 282M229 319L277 329" stroke="#a82b48" stroke-width="4"/><path d="M177 174L211 180M248 234L278 238" stroke="#367ab1" stroke-width="4"/>';}
 case 'sidepanels':return `<path d="M110 59L148 73L157 140L138 378L113 397L133 134L75 145Z M310 59L272 73L263 140L282 378L307 397L287 134L345 145Z" fill="${c}"/><path d="M124 64L140 76L149 141L127 387M296 64L280 76L271 141L293 387" fill="none" stroke="#ba2940" stroke-width="7"/><path d="M40 132L111 175M380 132L309 175" stroke="#ba2940" stroke-width="6"/><path d="M197 63L210 83L223 63Z" fill="#ba2940"/>`;
 case 'centennial':return '<path d="M37 128L112 175M383 128L308 175" stroke="#172d46" stroke-width="15"/>';
 case 'band06':return '<path d="M260 30V430" stroke="#17304a" stroke-width="35"/><path d="M260 30V430" stroke="#c5283e" stroke-width="17"/><path d="M40 131L111 175M380 131L309 175" stroke="#b59c61" stroke-width="5"/>';
 case 'polo14':{let lines='';for(let x=130;x<300;x+=14)lines+=`<path d="M${x} 40V410" stroke="#9fa4a6" stroke-opacity=".3" stroke-width=".7"/>`;return lines;}
 case 'pinstripe':{let out='';for(let x=126;x<296;x+=12)out+=`<path d="M${x} 45V410" stroke="${c}" stroke-width="1" opacity=".35"/>`;return out+'<path d="M248 32V410" stroke="#172d4b" stroke-width="34"/><path d="M248 32V410" stroke="#bf2e45" stroke-width="15"/>';}
 case 'shoulders22':return '<path d="M126 60L166 71L128 139L67 151M294 60L254 71L292 139L353 151" fill="#172a42"/><path d="M79 146L117 174M341 146L303 174" stroke="#cb3048" stroke-width="11"/>';
 case 'tiedye':return `<g fill="${c}" opacity=".72"><path d="M0 55Q160 180 420 40L380 105Q160 230 0 147Z"/><path d="M0 209Q130 132 250 246T460 268L410 370Q245 280 150 323T0 390Z"/><path d="M121 0Q212 127 157 220L207 218Q255 116 192 0Z"/></g><g fill="${c}" opacity=".23"><path d="M90 244Q136 194 179 231T269 273Q316 284 306 323T208 347Q173 321 131 346T89 298Q111 280 90 244Z"/><path d="M44 70Q120 49 153 87T238 107Q259 153 201 146T99 119Q51 132 44 70Z"/></g>`;
 case 'gradient18':{let out='';for(let y=84;y<420;y+=26)out+=`<path d="M0 ${y}H420V${y+13}H0Z" fill="${c}" opacity="${Math.min(.95,(y-40)/360)}"/>`;return out;}
 case 'redshoulder':return `<path d="M95 48L149 42L139 145L62 161M325 48L271 42L281 145L358 161" fill="${c}"/>`;
 case 'black16':return '<path d="M94 53L145 43L138 146L61 161" fill="#ca2c42"/><path d="M326 53L275 43L282 146L359 161" fill="#286fa8"/>';
 case 'dazzle':return `<g fill="${c}"><path d="M0 73L190 15L214 60L25 138Z M164 128L420 57L440 112L182 179Z M-20 207L191 154L218 207L0 279Z M151 276L420 190L440 254L173 332Z M0 353L155 309L188 377L0 437Z M240 374L400 318L430 391L268 440Z"/></g>`;
 default:return '';
}}
function collar(k){if(k.collar==='polo')return `<path d="M170 43L157 56L181 92L210 62L239 92L263 56L250 43Q210 77 170 43" fill="${k.collarFill||k.trim}" stroke="${k.collarEdge||k.accent}" stroke-width="2.5"/><path d="M210 61V117" stroke="${k.collarEdge||k.accent}" stroke-width="3"/><circle cx="216" cy="90" r="2" fill="#fff"/>`;
if(k.collar==='v')return `<path d="M170 43L210 85L250 43" fill="none" stroke="${k.trim}" stroke-width="13"/><path d="M173 42L210 77L247 42" fill="none" stroke="#eee9df" stroke-opacity=".4" stroke-width="2"/>`;
return `<path d="M170 43Q210 102 250 43" fill="none" stroke="${k.trim}" stroke-width="${k.collar==='rib'?15:10}"/>${k.collar==='rib'?'<path d="M170 43Q210 102 250 43" fill="none" stroke="#c9283d" stroke-width="5"/>':''}<path d="M172 47Q210 96 248 47" fill="none" stroke="#f5f4eb" stroke-opacity=".2" stroke-width="1.3"/>`;}
function garment(k,view='whole',mini=false){const id='kr-'+(++svgSerial);const outline=k.year<=1994?'M119 63L170 43Q210 65 250 43L301 63Q338 105 376 150L312 190L290 153L301 389Q210 406 119 389L130 153L108 190L44 150Q82 105 119 63Z':shirtShape;const vb=view==='collar'?'135 20 150 145':view==='pattern'?'125 125 170 210':'0 0 420 440';return `<svg viewBox="${vb}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"><defs><clipPath id="${id}-clip"><path d="${outline}"/></clipPath><linearGradient id="${id}-fold"><stop stop-color="#000" stop-opacity=".22"/><stop offset=".22" stop-color="#fff" stop-opacity=".12"/><stop offset=".37" stop-color="#000" stop-opacity=".07"/><stop offset=".52" stop-color="#fff" stop-opacity=".2"/><stop offset=".72" stop-color="#000" stop-opacity=".04"/><stop offset="1" stop-color="#000" stop-opacity=".25"/></linearGradient><linearGradient id="${id}-drop" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#fff" stop-opacity=".13"/><stop offset=".8" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".15"/></linearGradient><pattern id="${id}-weave" width="4" height="4" patternUnits="userSpaceOnUse"><path d="M0 0L4 4M-1 3L1 5" stroke="#fff" stroke-opacity=".14" stroke-width=".6"/></pattern></defs><path d="${outline}" fill="${k.base}" stroke="#14233d" stroke-opacity=".22"/><g clip-path="url(#${id}-clip)">${pattern(k,id)}<path d="M0 0H420V440H0Z" fill="url(#${id}-fold)"/><path d="M0 0H420V440H0Z" fill="url(#${id}-drop)"/>${mini?'':`<path d="M0 0H420V440H0Z" fill="url(#${id}-weave)"/>`}<path d="M131 71Q149 106 135 151M289 71Q271 106 285 151M79 148L111 171M341 148L309 171M142 377Q210 389 278 377" stroke="#fff" stroke-opacity=".2" fill="none" stroke-width="1.3"/><path d="M143 153Q161 197 145 254M276 155Q260 227 278 300M151 318L146 377M269 320L274 377" stroke="#000" stroke-opacity=".07" fill="none" stroke-width="4"/></g><path d="M170 43Q210 65 250 43Q210 95 170 43" fill="#132236" opacity=".8"/>${collar(k)}${view==='collar'&&k.id==='stripes'?'<path d="M199 54H221V63H199Z" fill="#d8bf8d"/><path d="M222 55L263 29" stroke="#af2537" stroke-width="1.4"/>':''}</svg>`;}
function meta(k){return `${k.year} ${k.edition} · ${k.maker}`;}
function visible(){const era=$('kit-era').value,family=$('kit-family').value;return collection.filter(k=>(era==='all'||String(Math.floor(k.year/10)*10)===era)&&(family==='all'||k.family===family));}
function announce(text){$('kit-status').textContent=text;}
function favoriteStatus(){const isPick=current===favorite;$('kit-save').setAttribute('aria-pressed',String(isPick));$('kit-save').textContent=isPick?'★ Your favorite':'☆ Make this my favorite';$('kit-favorite-jump').hidden=!favorite;$('kit-saved').textContent=favorite?`Your pick: ${meta(kitMap[favorite])}. ${storageOK?'Saved in this browser.':'Kept for this visit; browser storage unavailable.'}`:'Your favorite stays in this browser. No sign-in.';}
function renderRail(){const items=visible();$('kit-count').textContent=`${items.length} of ${collection.length} shirts`;$('kit-empty').hidden=items.length>0;$('kit-rail').hidden=!items.length;$('kit-exhibit').hidden=!items.length;$('kit-rail').innerHTML=items.map((k,i)=>`<button type="button" data-kit="${k.id}" tabindex="${k.id===current||(!items.some(x=>x.id===current)&&i===0)?0:-1}" aria-pressed="${k.id===current}" aria-label="${escape(meta(k)+', '+k.label)}"><span class="kit-thumb">${garment(k,'whole',true)}</span><span class="kit-tile-year">${k.year} <small>${escape(k.edition)}</small></span><span class="kit-tile-name">${escape(k.label)}</span></button>`).join('');
$('kit-prev').disabled=items.length<2;$('kit-next').disabled=items.length<2;}
function renderExhibit(){const k=kitMap[current];$('kit-art').innerHTML=garment(k,detail);$('kit-meta').textContent=meta(k);$('kit-name').textContent=k.name;$('kit-fact').textContent=k.fact;$('kit-story').textContent=k.reading;$('kit-detail-title').textContent=detail==='collar'?'AT THE COLLAR':detail==='pattern'?'READ THE PATTERN':'THE DESIGN READING';$('kit-detail-text').textContent=detail==='collar'?k.collarNote:k.patternNote;$('kit-source').href=k.source;$('kit-source').textContent=(k.sourceLabel||'Federation source & context')+' ↗';$('kit-visual-source').hidden=!k.visualSource;if(k.visualSource){$('kit-visual-source').href=k.visualSource;$('kit-visual-source').textContent=(k.visualLabel||'Secondary visual archive')+' ↗';}$('kit-stage-year').textContent=String(k.year).slice(-2);$('kit-view-label').textContent=detail==='whole'?'Original graphic study':detail==='pattern'?'Pattern close-up · illustrative':'Collar close-up · illustrative';$('kit-view-note').textContent=detail==='whole'?'Select Pattern or Collar to inspect the visual idea.':'Close-up of our illustration. Seams, scale and texture are interpretive.';document.querySelectorAll('[data-kit-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kitView===detail)));$('kit-exhibit').dataset.view=detail;favoriteStatus();}
function select(id,{focus=false,reset=false}={}){if(!kitMap[id])return;current=id;if(reset){$('kit-era').value='all';$('kit-family').value='all';renderRail();}else document.querySelectorAll('[data-kit]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.kit===id));b.tabIndex=b.dataset.kit===id?0:-1;});renderExhibit();const btn=document.querySelector(`[data-kit="${id}"]`);if(btn&&focus){btn.focus();btn.scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'});}announce(`${meta(kitMap[id])}: ${kitMap[id].label}. Selected.`);}
const pairNotes={
 'states20|away22':['Contour is not dye.','The 2020 States study is built from irregular lines. The 2022 away study is built from fluid areas of color. From far away both can read as busy blue; close up, they speak different visual languages.'],
 'sash|away10':['Same diagonal, reversed contrast.','The home study lets a silver-gray sash sit quietly against white. The away study gives a white sash a dark blue field. Their common line establishes a family resemblance before the eye gets to any badge.'],
 'waldo12|stripes':['From marching rhythm to flowing stripes.','The Waldo study repeats straight red-and-white bands. The 2026 study gives those bands a wave. One is regular and insistent; the other suggests motion. The family connection is our design reading, not a manufacturing lineage claim.'],
 'polo14|bomb':['Same summer. Very different voices.','The home study gives its collar and fine pinstripes room to breathe. Bomb Pop fills the surface with large color blocks. Which shirt feels like a permanent national uniform—and which feels like a summer you can date?'],
 'denim|stars':['Same star. Different volume.','The 1994 study makes its stars light, large and unmistakable. The 2026 study lowers the contrast until they emerge from the navy. Recognition can come from a repeated motif without repeating its loudness.'],
 'bomb|icon24':['From blocks to motion.','The 2014 study holds its three colors apart. The 2024 study lets their edges distort and blend. U.S. Soccer explicitly names 2014 as a reference for the 2024 away design; the visual comparison shows one way to read that connection.'],
 'classic24|icon24':['One palette. Two jobs.','The 2024 home study concentrates color at the openings; the away study lets it take over the surface. Minimal and expressive can belong to the same family.'],
 'stripes|stars':['A shared year, two registers.','The light Stripes study announces itself; the dark Stars study asks you to look closer. Compare the amount of contrast rather than assuming that one design is more patriotic than the other.']
};
function compareReading(a,b){const known=pairNotes[a.id+'|'+b.id]||pairNotes[b.id+'|'+a.id];if(known)return known;const gap=Math.abs(a.year-b.year);if(a.family===b.family)return [`${familyLabels[a.family]}, ${gap?gap+' years apart':'two ways'}.`,`Both studies build around ${familyLabels[a.family].toLowerCase()}. Compare the scale of the motif, the contrast with the base, and where the eye lands first. The shared category is our design reading, not an official kit classification.`];if(a.year===b.year)return ['One year. Two visual identities.',`These ${a.year} studies choose different routes: ${familyLabels[a.family].toLowerCase()} and ${familyLabels[b.family].toLowerCase()}. Cover the year labels and look at the shape, contrast and collar. Which detail makes each unmistakable?`];return ['What makes it feel like the USA?',`One study leads with ${familyLabels[a.family].toLowerCase()}, the other with ${familyLabels[b.family].toLowerCase()}. Compare where the color lives and how much empty space surrounds it. This is an editorial comparison of visual ideas, not a ranking or a performance claim.`];}
function renderCompare(){const a=kitMap[compareA],b=kitMap[compareB];$('kit-compare-left').value=compareA;$('kit-compare-right').value=compareB;for(const [side,k] of [['a',a],['b',b]]){$('kit-compare-'+side+'-art').innerHTML=garment(k);$('kit-compare-'+side+'-title').textContent=meta(k);$('kit-compare-'+side+'-name').textContent=k.label;$('kit-compare-'+side+'-source').href=k.source;$('kit-compare-'+side+'-source').textContent=(k.sourceLabel?'Historical reference':'Federation context')+' ↗';}
const [title,note]=compareReading(a,b);$('kit-compare-title').textContent=title;$('kit-compare-reading').textContent=note;$('kit-compare-traits').innerHTML=`<div><span>Design family</span><b>${escape(familyLabels[a.family])}</b><b>${escape(familyLabels[b.family])}</b></div><div><span>Year</span><b>${a.year}</b><b>${b.year}</b></div><div><span>Our visual shorthand</span><b>${escape(a.label)}</b><b>${escape(b.label)}</b></div>`;}
function openCompare(a=current,b=favorite){compareA=a;compareB=b&&b!==a?b:(a==='stars'?'denim':a==='denim'?'stars':a==='icon24'?'bomb':a==='bomb'?'icon24':collection.find(k=>k.id!==a&&k.family===kitMap[a].family)?.id||'denim');$('kit-comparison').hidden=false;$('kit-compare-open').setAttribute('aria-expanded','true');renderCompare();$('kit-compare-left').focus();$('kit-comparison').scrollIntoView({block:'start',behavior:'auto'});announce('Comparison opened. Choose two shirts independently of the gallery filters.');}
$('kit-rail').addEventListener('click',e=>{const b=e.target.closest('[data-kit]');if(b)select(b.dataset.kit)});
$('kit-rail').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||!e.target.closest('[data-kit]'))return;e.preventDefault();const items=visible(),i=items.findIndex(k=>k.id===e.target.closest('[data-kit]').dataset.kit);const n=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowRight'?1:-1)+items.length)%items.length;select(items[n].id,{focus:true});});
for(const id of ['kit-era','kit-family'])$(id).addEventListener('change',()=>{renderRail();const items=visible();if(items.length&&!items.some(k=>k.id===current))select(items[0].id);announce(`${items.length} shirts match the filters.${!items.length?' Clear the filters to see the collection.':''}`);});
$('kit-reset').addEventListener('click',()=>{$('kit-era').value='all';$('kit-family').value='all';renderRail();announce(`Showing all ${collection.length} shirts.`)});
for(const [id,step] of [['kit-prev',-1],['kit-next',1]])$(id).addEventListener('click',()=>{const items=visible();if(!items.length)return;const i=items.findIndex(k=>k.id===current);const next=items[(Math.max(i,0)+step+items.length)%items.length];select(next.id);document.querySelector(`[data-kit="${next.id}"]`)?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'});});
document.querySelectorAll('[data-kit-view]').forEach(b=>b.addEventListener('click',()=>{detail=b.dataset.kitView;renderExhibit();announce(`${detail==='whole'?'Whole shirt':detail+' detail'}: ${meta(kitMap[current])}.`)}));
$('kit-save').addEventListener('click',()=>{favorite=current;try{localStorage.setItem(key,favorite);storageOK=true}catch{storageOK=false}favoriteStatus();announce($('kit-saved').textContent)});
$('kit-favorite-jump').addEventListener('click',()=>{if(favorite)select(favorite,{focus:true,reset:true})});
$('kit-compare-open').addEventListener('click',()=>openCompare());$('kit-compare-close').addEventListener('click',()=>{$('kit-comparison').hidden=true;$('kit-compare-open').setAttribute('aria-expanded','false');$('kit-compare-open').focus();announce('Comparison closed.')});
$('kit-comparison').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();$('kit-compare-close').click();}});
$('kit-compare-swap').addEventListener('click',()=>{[compareA,compareB]=[compareB,compareA];renderCompare();announce('Comparison sides swapped.')});
for(const [id,side] of [['kit-compare-left','left'],['kit-compare-right','right']])$(id).addEventListener('change',()=>{if(side==='left'){const previous=compareA;compareA=$(id).value;if(compareA===compareB)compareB=previous;}else{const previous=compareB;compareB=$(id).value;if(compareA===compareB)compareA=previous;}renderCompare();announce(`Comparing ${meta(kitMap[compareA])} and ${meta(kitMap[compareB])}.`)});
$('kit-pair-presets').addEventListener('click',e=>{const b=e.target.closest('[data-kit-pair]');if(b){const [a,c]=b.dataset.kitPair.split('|');openCompare(a,c)}});
document.querySelectorAll('.shirt__btn').forEach(b=>b.addEventListener('click',()=>{const on=b.closest('.shirt').classList.toggle('alive');b.setAttribute('aria-pressed',String(on))}));
const options=collection.map(k=>`<option value="${k.id}">${escape(meta(k)+' — '+k.label)}</option>`).join('');$('kit-compare-left').innerHTML=options;$('kit-compare-right').innerHTML=options;
const eras=[...new Set(collection.map(k=>Math.floor(k.year/10)*10))];$('kit-era').innerHTML='<option value="all">Every era</option>'+eras.map(y=>`<option value="${y}">${y}s</option>`).join('');
$('kit-total').textContent=collection.length;root.classList.add('kit-room-ready');renderRail();renderExhibit();renderCompare();
})();
