(()=>{'use strict';
const release='https://www.ussoccer.com/stories/2026/03/nike-unveils-new-national-team-stars-stripes-jerseys-kits-fifa-world-cup';
const kits={
denim:{year:'94',meta:'1994 AWAY / ADIDAS',name:'The denim one.',story:"A shirt that looks like it came from your closet, then walks onto the world stage. The 1994 away shirt makes American everyday style part of football's visual language.",detail:'Oversized stars against a denim-like field. This graphic study isolates that idea; it is not a replica or a product image.',focus:'The star field makes the shirt recognizable at a distance. Try the 2026 Stars shirt next: the same motif can feel completely different.',title:'LOOK FOR THE CONTRAST',color:'#5d87b5',source:'https://www.ussoccer.com/stories/2026/05/usmnt/26-moments-usa-breaks-through-1994-fifa-world-cup-home-soil'},
sash:{year:'10',meta:'2010 HOME / NIKE',name:'One diagonal.',story:'The white sash shirt carries the Donovan-versus-Algeria memory in this collection. One strong diagonal does the visual work; the rest of the shirt gives it room.',detail:'This simplified study focuses on the sash, not manufacturer marks or exact construction. A small change in angle can make a very quiet shirt feel fast.',focus:'Follow the line from shoulder to waist. It moves the eye across the body instead of letting it settle in the center. This is our design reading.',title:'FOLLOW THE LINE',color:'#f4f5f4',source:'https://www.ussoccer.com/history/timeline'},
bomb:{year:'14',meta:'2014 AWAY / NIKE',name:'Summer in blocks.',story:'The Bomb Pop. Blue, white and red, with a nickname that turns a national-team shirt into an American summer memory. In Gordon’s words: “The shirt was beautiful.”',detail:'Three uninterrupted bands do the work. No complicated pattern needed: their order and proportion are the personality.',focus:'Compare this straight color break with the movement in the 2026 Stripes study. Both use the same palette; their visual rhythm is different. This is design interpretation.',title:'READ THE COLOR BLOCKS',color:'#df3449',source:'https://www.ussoccer.com/2024-jersey'},
stripes:{year:'26',meta:'2026 / NIKE / STRIPES',name:'Loud and proud.',story:'The light half of the 2026 collection makes the flag an unmistakable starting point. The official launch describes a design process shaped by player feedback, from fabric weight to freedom of movement.',detail:'The shirt is more than its surface: an “Inner Pride” mark sits inside the collar. The original illustration simplifies the stripes and omits official logos.',focus:'Look inside the collar. U.S. Soccer describes the “Inner Pride” mark as a reminder of the motivation carried onto the field. The marker here shows its location, not an exact reproduction.',title:'AN INSIDE DETAIL',color:'#f7f5f0',source:release},
stars:{year:'26',meta:'2026 / NIKE / STARS',name:'The quiet stars.',story:'The dark half of the 2026 collection has a different register: a shirt that can live away from the field, too. Gordon’s own navy number 4, below, makes that connection personal.',detail:'Our graphic study uses a dark star field to explore that quieter mood. Its lettering and badge are deliberately omitted; it is not an official replica.',focus:'The launch introduced bespoke Stars and Stripes typefaces for U.S. Soccer. Even the numbers now belong to the wider identity. Follow the official launch for the real lettering.',title:'IDENTITY IN THE DETAILS',color:'#14263d',source:release}};
const art=document.getElementById('kit-art');if(!art)return;
const path='M115 45 L155 27 Q190 56 225 27 L265 45 L324 125 L273 160 L248 129 L253 350 Q190 363 127 350 L132 129 L107 160 L56 125 Z';
function svg(k){let pattern='';if(k==='denim'||k==='stars'){const c=k==='denim'?'#e4ecf3':'#263d54';for(let y=70;y<360;y+=80)for(let x=105;x<285;x+=72)pattern+=`<path d="M${x} ${y-23} l7 16 18 2 -14 12 4 18 -15 -10 -16 10 5 -18 -14 -12 18 -2Z" fill="${c}"/>`;}
if(k==='sash')pattern='<path d="M104 50 L143 38 L280 320 L239 350Z" fill="#b9c1c9"/>';
if(k==='bomb')pattern='<path d="M40 20H340V108H40Z" fill="#2675bc"/><path d="M40 108H340V165H40Z" fill="#f5f4ed"/>';
if(k==='stripes')for(let y=85;y<360;y+=70)pattern+=`<path d="M50 ${y} Q140 ${y-25} 220 ${y} T335 ${y} L335 ${y+32} Q240 ${y+55} 175 ${y+32} T50 ${y+32}Z" fill="#c8364b"/>`;
return `<svg viewBox="0 0 380 400" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="shirt-clip"><path d="${path}"/></clipPath><linearGradient id="fold"><stop stop-color="#000" stop-opacity=".13"/><stop offset=".35" stop-color="#fff" stop-opacity=".12"/><stop offset=".7" stop-color="#000" stop-opacity=".03"/><stop offset="1" stop-color="#000" stop-opacity=".22"/></linearGradient><pattern id="weave" width="4" height="4" patternUnits="userSpaceOnUse"><path d="M0 0L4 4" stroke="#fff" stroke-opacity=".12" stroke-width=".5"/></pattern></defs><path d="${path}" fill="${kits[k].color}" stroke="#14233d" stroke-opacity=".3"/><g clip-path="url(#shirt-clip)">${pattern}<path d="M0 0H380V400H0Z" fill="url(#weave)"/><path d="M0 0H380V400H0Z" fill="url(#fold)"/></g><path d="M155 27Q190 73 225 27" stroke="${k==='denim'?'#c83245':'#10243d'}" stroke-width="11" fill="none"/><path d="M132 129L145 85M248 129L235 85M140 340Q190 347 240 340" fill="none" stroke="#11223f" stroke-opacity=".2"/><g class="detail-marker"><circle cx="190" cy="${k==='stripes'?48:170}" r="32" fill="none" stroke="#f6b53b" stroke-width="3" stroke-dasharray="5 4"/><path d="M222 ${k==='stripes'?48:170}H300" stroke="#f6b53b" stroke-width="2"/><circle cx="300" cy="${k==='stripes'?48:170}" r="5" fill="#f6b53b"/></g></svg>`;}
let current='denim',detail=false,favorite=null;const key='usa26-kit-room-favorite-v1';try{const value=localStorage.getItem(key);if(kits[value])favorite=value}catch{}
const $=id=>document.getElementById(id);
function status(){ $('kit-save').setAttribute('aria-pressed',String(current===favorite));$('kit-save').innerHTML=current===favorite?'Your favorite <span aria-hidden="true">★</span>':'Keep this as my favorite <span aria-hidden="true">☆</span>'; $('kit-saved').textContent=favorite?'Your pick: '+kits[favorite].meta+'. Saved only here.':'Your choice stays in this browser.';}
function render(){const d=kits[current];art.innerHTML=svg(current);document.querySelector('.kit-stage-year').textContent=d.year;$('kit-meta').textContent=d.meta;$('kit-name').textContent=d.name;$('kit-story').textContent=d.story;$('kit-detail-title').textContent=detail?'DETAIL / '+d.title:d.title;$('kit-detail-text').textContent=detail?d.focus:d.detail;$('kit-source').href=d.source;$('kit-source').textContent=current==='sash'?'U.S. Soccer historical timeline ↗':current==='bomb'?'U.S. Soccer on the 2014 design legacy ↗':'Explore the official story ↗';document.querySelector('.kit-stage').classList.toggle('is-detail',detail);status();}
document.querySelectorAll('[data-kit]').forEach(btn=>btn.addEventListener('click',()=>{current=btn.dataset.kit;document.querySelectorAll('[data-kit]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));render()}));
$('kit-detail-toggle').addEventListener('click',()=>{detail=!detail;$('kit-detail-toggle').setAttribute('aria-pressed',String(detail));$('kit-detail-toggle').innerHTML=detail?'Show the whole shirt <span aria-hidden="true">−</span>':'Inspect the detail <span aria-hidden="true">＋</span>';render()});
$('kit-save').addEventListener('click',()=>{favorite=current;try{localStorage.setItem(key,favorite);status()}catch{status();$('kit-saved').textContent='Your pick: '+kits[current].meta+'. Storage is unavailable; kept for this visit.'}});
document.querySelectorAll('.shirt__btn').forEach(btn=>btn.addEventListener('click',()=>{const on=btn.closest('.shirt').classList.toggle('alive');btn.setAttribute('aria-pressed',String(on))}));render();
})();
