/* Progressive enhancement: every principal route and fixture date works without JS. */
(()=>{'use strict';
const now=()=>Date.now();
function freshness(){
 document.querySelectorAll('[data-fixture]').forEach(board=>{
  const start=Date.parse(board.dataset.fixture),status=board.querySelector('.match-status'),tag=board.querySelector('.fixture-top .eyebrow');
  if(!Number.isFinite(start))return;
  if(now()>=start){if(status)status.textContent='Result not yet verified';if(tag)tag.textContent='LAST LISTED FIXTURE';board.querySelector('.fixture-note').textContent='Scheduled kickoff has passed. Check U.S. Soccer for the result; this page does not infer live status.';board.querySelector('a[download]')?.setAttribute('hidden','');}
  else {status.textContent='Scheduled · Oct 6';}
 });
 if(now()>Date.parse('2026-10-08T07:00:00Z'))document.querySelectorAll('[data-freshness]').forEach(el=>{el.textContent='Archived source snapshot · October 6, 2026. Follow the official sources for newer updates.';});
}
freshness();setInterval(freshness,60000);
const routes={new:['A good first lap: the life, the summer, then a little play.',[['soccer-journey.html',"Number 4: Gordon’s journey"],['summer.html#frames','The summer in six frames'],['play.html','Find your game in the arcade']]],summer:['Start with the people, find the night, then keep the whole summer.',[['friends.html','Find your chapter in The Friends'],['run.html#turkiye','June 25: the SoFi chapter'],['summer.html#games','The nights and the rooms']]],football:['Read the current players, study the opponent, then follow the wider team update.',[['squad.html','The current squad and the 2030 watchlist'],['canada.html','Canada: the October 6 opponent notebook'],['now.html','The team now: results and next dates']]]};
document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const [intro,links]=routes[button.dataset.route];const target=document.getElementById('route-result');target.replaceChildren();const p=document.createElement('p');p.textContent=intro;target.append(p);const ol=document.createElement('ol');links.forEach(([url,title])=>{const li=document.createElement('li'),a=document.createElement('a');a.href=url;a.textContent=title+' →';li.append(a);ol.append(li);});target.append(ol);}));
document.querySelectorAll('.chapter-menu').forEach(menu=>{menu.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.open=false;menu.querySelector('summary').focus();}});document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.open=false;});});
// Existing flip cards are custom controls. Add keyboard parity without changing their saved state.
document.querySelectorAll('.flip:not(button)').forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.click();}});});
// Native dialogs keep focus within the photo viewer and return it to the triggering photo.
document.addEventListener('click',()=>{const dialog=document.querySelector('dialog.lb');if(dialog&&!dialog.getAttribute('aria-label'))dialog.setAttribute('aria-label','Photo viewer');});
})();
// Preserve shared bookmarks from the former home page when its chapters move to the archive.
if(/\/(?:index\.html)?$/.test(location.pathname)&&['top','numbers','result','frames','deep-dives','games','signal'].includes(location.hash.slice(1)))location.replace('summer.html'+location.hash);
(()=>{const phases={build:['01 / BUILD THROUGH PRESSURE','Can the next player face forward?','Watch the first receiver, not only the goalkeeper. A clean first pass helps only if the next player can turn, combine, or choose a sensible longer option.','a supporting angle and a second pass ready before the first arrives.','M48 165L135 92L215 125',135,92],advance:['02 / ADVANCE INTO SPACE','Who makes the pitch bigger?','Watch the wide player and the teammate inside. Width can stretch a defense, but someone still needs to receive between its lines and face the goal.','a forward-facing receiver, rather than a pass that merely moves possession sideways.','M215 125L315 66L345 165',315,66],create:['03 / CREATE THE CHANCE','What turned territory into danger?','Separate the route forward from the final action. A combination, run, cross, set piece or forced mistake can each produce a chance. Notice where the shot actually comes from.','repeatable ways into useful shooting positions, not just a high possession total.','M315 66L430 165L476 165',430,165],protect:['04 / PROTECT AFTER LOSING IT','Who is already behind the attack?','As the wide players advance, watch the teammates left in support. Their spacing helps cover central lanes and compete for a loose second ball.','cover behind the ball before the turnover happens. This protective structure is often called rest defense.','M345 165L215 205L135 238',215,205]};document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-phase]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const [label,title,body,look,path,x,y]=phases[b.dataset.phase];document.getElementById('phase-copy').innerHTML='<p class="eyebrow">'+label+'</p><h3>'+title+'</h3><p>'+body+'</p><p><strong>Look for:</strong> '+look+'</p>';document.getElementById('phase-path').setAttribute('d',path);document.getElementById('phase-focus').setAttribute('cx',x);document.getElementById('phase-focus').setAttribute('cy',y);document.getElementById('pitch-title').textContent='Illustrative pitch: '+label.toLowerCase();document.getElementById('pitch-desc').textContent=look;}));})();

(()=>{const source=document.getElementById('window-chart-data');if(!source)return;const matches=JSON.parse(source.textContent),modes={shots:['Shots',20],sot:['Shots on target',10],corners:['Corners',15]};document.querySelectorAll('[data-window-metric]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.windowMetric,[label,max]=modes[key];document.querySelectorAll('[data-window-metric]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));matches.forEach(match=>{const panel=document.querySelector('[data-window-match="'+match.id+'"]');panel.querySelector('.window-metric-name').textContent=label+' · scale 0–'+max;panel.querySelectorAll('.metric-bar').forEach((row,i)=>{row.querySelector('b').textContent=match[key][i];row.querySelector('i').style.width=(match[key][i]/max*100)+'%';});});}));})();
