(()=>{'use strict';
const root=document.querySelector('[data-scout-explorer]');
if(root){
 const rows=[...root.querySelectorAll('.player-row')],profiles=[...root.querySelectorAll('[data-player]')],search=root.querySelector('#player-search'),position=root.querySelector('#player-position'),cohort=root.querySelector('#player-cohort'),age=root.querySelector('#player-age'),caps=root.querySelector('#player-caps'),count=root.querySelector('.roster-count'),empty=root.querySelector('.scout-empty'),bench=root.querySelector('.compare-bench'),selected=[];
 if(root.hasAttribute('data-no-stats')){age.closest('label').hidden=true;caps.closest('label').hidden=true;}
 const byId=new Map(profiles.map(p=>[p.id,p]));
 const fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 function show(id,scroll=false){if(!byId.has(id))return;profiles.forEach(p=>p.hidden=p.id!==id);rows.forEach(r=>r.setAttribute('aria-current',String(r.hash==='#'+id)));if(scroll&&matchMedia('(max-width:760px)').matches)byId.get(id).scrollIntoView({block:'start',behavior:'instant'});}
 function bucket(value,key){if(key==='all')return true;if(value==='')return false;const n=Number(value);return key==='u21'?n<21:key==='21-25'?n>=21&&n<=25:key==='26+'?n>=26:key==='0'?n===0:key==='1-9'?n>=1&&n<=9:key==='10-29'?n>=10&&n<=29:n>=30;}
 function filter(){const q=fold(search.value.trim());let visible=[];rows.forEach(r=>{const hit=(!q||fold(r.textContent).includes(q))&&(position.value==='all'||r.dataset.position===position.value)&&(cohort.value==='all'||r.dataset.cohort.split(' ').includes(cohort.value))&&bucket(r.dataset.age,age.value)&&bucket(r.dataset.caps,caps.value);r.hidden=!hit;if(hit)visible.push(r);});count.textContent=visible.length+' '+(visible.length===1?'player':'players')+' shown · select a name to inspect';empty.hidden=!!visible.length;const current=rows.find(r=>r.getAttribute('aria-current')==='true');if(visible.length&&(!current||current.hidden))show(visible[0].hash.slice(1));if(!visible.length)profiles.forEach(p=>p.hidden=true);}
 function addText(tag,text,parent){const el=document.createElement(tag);el.textContent=text;parent.appendChild(el);return el;}
 function compare(){root.querySelectorAll('[data-compare]').forEach(b=>{const chosen=selected.includes(b.dataset.compare);b.setAttribute('aria-pressed',String(chosen));b.textContent=chosen?'Remove from comparison':'Add to comparison';});bench.hidden=!selected.length;const output=bench.querySelector('[data-compare-output]');output.replaceChildren();if(selected.length<2){addText('p','Choose one more player. Compare roles and evidence, not a forecast of the 2030 squad.',output);return;}const table=addText('table','',output),thead=table.createTHead(),head=thead.insertRow();addText('th','Lens',head);selected.forEach(id=>addText('th',byId.get(id).dataset.name,head));const body=table.createTBody();[['Age','age'],['Role','role'],['Club¹','club'],['Caps²','caps'],['Goals²','goals'],['Status','status'],['Strength³','strength'],['Question³','question']].filter(([label,key])=>!root.hasAttribute('data-no-stats')||!['age','caps','goals'].includes(key)).forEach(([label,key])=>{const tr=body.insertRow();const th=addText('th',label,tr);th.scope='row';selected.forEach(id=>addText('td',byId.get(id).dataset[key]||'Not asserted',tr));});addText('p','¹ Club status is dated in each profile. ² Senior international totals at the cited snapshot, where verified. ³ Editorial analysis, not an official scouting grade.',output).className='fact-note';}
 rows.forEach(r=>r.addEventListener('click',e=>{e.preventDefault();const id=r.hash.slice(1);history.replaceState(null,'','#'+id);show(id,true);}));
 [search,position,cohort,age,caps].forEach(el=>el.addEventListener(el===search?'input':'change',filter));
 root.querySelectorAll('[data-compare]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.compare,index=selected.indexOf(id);if(index>=0)selected.splice(index,1);else{if(selected.length===2)selected.shift();selected.push(id);}compare();}));
 const clear=bench.querySelector('[data-clear-compare]');clear.addEventListener('click',()=>{selected.length=0;compare();});
 document.documentElement.classList.add('scout-enhanced');
 let requested=location.hash.slice(1);if(byId.has(requested)){const row=rows.find(r=>r.hash==='#'+requested);if(row&&!row.dataset.cohort.split(' ').includes(cohort.value))cohort.value='all';}else requested=rows[0]?.hash.slice(1);filter();if(requested)show(requested);
 window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(byId.has(id)){cohort.value='all';position.value='all';age.value='all';caps.value='all';search.value='';filter();show(id,true);}});
}
const lenses=document.querySelector('[data-match-lenses]');if(lenses){const data=JSON.parse(document.getElementById('lens-data').textContent),copy=document.getElementById('lens-copy'),path=document.getElementById('lens-path'),focus=document.getElementById('lens-focus');lenses.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const d=data[b.dataset.lens];if(!d)return;lenses.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));copy.querySelector('h3').textContent=d.title;copy.querySelector('[data-lens-body]').textContent=d.body;copy.querySelector('[data-lens-watch]').textContent=d.watch;path.setAttribute('d',d.path);focus.setAttribute('cx',d.x);focus.setAttribute('cy',d.y);}));}
})();
