/* Progressive enhancement: all 15 illustrated stills remain readable without JavaScript. */
(()=>{'use strict';const guide=document.querySelector('.tactics-guide');if(!guide)return;
const tabs=[...guide.querySelectorAll('[data-scene-tab]')],scenes=[...guide.querySelectorAll('.tactic-scene')],live=guide.querySelector('[role=status]');let current=0;const states=scenes.map(()=>0);
function announce(){const s=scenes[current];live.textContent=`${tabs[current].textContent.trim()}. ${s.querySelectorAll('[data-tactic-state] h4')[states[current]].textContent}. Still ${states[current]+1} of 3.`;}
function state(n,notify=true){states[current]=Math.max(0,Math.min(2,n));const s=scenes[current],all=s.classList.contains('show-all');s.querySelectorAll('[data-tactic-state]').forEach((f,i)=>{f.hidden=!all&&i!==states[current]});s.querySelectorAll('[data-state-go]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===states[current])));s.querySelector('[data-state-prev]').disabled=states[current]===0;s.querySelector('[data-state-next]').disabled=states[current]===2;if(notify)announce();}
function scene(n,notify=true){current=n;scenes.forEach((s,i)=>{s.hidden=i!==n});tabs.forEach((b,i)=>{b.setAttribute('aria-selected',String(i===n));b.tabIndex=i===n?0:-1});state(states[n],notify);}
guide.classList.add('enhanced');guide.querySelector('.tactic-tabs').setAttribute('role','tablist');tabs.forEach((b,i)=>{b.setAttribute('role','tab');b.id='tactic-tab-'+i;b.setAttribute('aria-controls','tactic-'+i);b.addEventListener('click',e=>{e.preventDefault();scene(i)});b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%5;if(e.key==='ArrowLeft')next=(i+4)%5;if(e.key==='Home')next=0;if(e.key==='End')next=4;if(e.key===' '){e.preventDefault();scene(i);return}if(next!==undefined){e.preventDefault();scene(next);tabs[next].focus()}})});
scenes.forEach((s,i)=>{s.setAttribute('role','tabpanel');s.setAttribute('aria-labelledby','tactic-tab-'+i);s.querySelector('.state-controls').hidden=false;s.querySelector('[data-all-stills]').hidden=false;s.querySelectorAll('[data-state-go]').forEach(b=>b.addEventListener('click',()=>state(Number(b.dataset.stateGo))));s.querySelector('[data-state-prev]').addEventListener('click',()=>state(states[current]-1));s.querySelector('[data-state-next]').addEventListener('click',()=>state(states[current]+1));s.querySelector('[data-all-stills]').addEventListener('click',e=>{const all=s.classList.toggle('show-all');e.target.setAttribute('aria-pressed',String(all));e.target.textContent=all?'Show one still at a time':'Show all three stills';state(states[current])})});
guide.querySelectorAll('[data-pick-scene]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const n=Number(a.dataset.pickScene);scene(n);tabs[n].focus();tabs[n].scrollIntoView({block:'nearest'})}));function hash(){const m=location.hash.match(/^#tactic-([0-4])$/);if(m)scene(Number(m[1]));}scene(0,false);hash();addEventListener('hashchange',hash);
})();
