"""Five editorial, source-separated tactical illustrations; all stills exist without JS."""
from pathlib import Path
from html import escape as h
import json
root=Path(__file__).resolve().parents[2]
S={
'coach':('Jesse Marsch: a national identity','https://elitesoccercoaching.net/player-and-coach-development/jesse-marsch-a-national-identity'),
'peru':('Canada Soccer: Canada 2–0 Peru, October 3','https://canadasoccer.com/match/6619/'),
'mexico':('U.S. Soccer: USA–Mexico match report','https://www.ussoccer.com/stories/2026/10/usmnt-vs-mexico-match-recap-highlights-arizona'),
'preview':('U.S. Soccer: Canada match preview','https://www.ussoccer.com/stories/2026/10/usmnt/canada-match-st-paul-minnesota')}
def a(team,role,x,y):return [team,role,x,y]
def route(kind,*points):return [kind,list(points)]
def state(title,copy,ball,moves={},routes=[],space=None,cover=None):return dict(title=title,copy=copy,ball=ball,moves=moves,routes=routes,space=space,cover=cover)
scenes=[
 dict(tab='Draw pressure',title='One pass can bring a crowd.',take='Watch the next Canadian player as well as the first one. The U.S. needs an exit before the pressure arrives.',actors=[a('usa','GK',8,50),a('usa','CB',22,30),a('usa','CB',22,70),a('usa','6',37,50),a('usa','FB',30,10),a('can','9',36,29),a('can','9',41,61),a('can','MID',48,45),a('can','W',43,15)],states=[
 state('The invitation','A short pass brings the ball toward the first challenger. Keep an eye on the players behind that challenger, too.',(10,47),routes=[route('pass',(8,50),(22,30))]),
 state('The crowd arrives','The first presser approaches the centre-back; a teammate approaches the wide outlet. The pressure is a team action.',(24,27),{'5':(27,30),'8':(34,15)},[route('press',(36,29),(27,30)),route('press',(43,15),(34,15))]),
 state('Look at the next receiver','The holding midfielder may look free before the pass. Watch whether the supporting Canadian midfielder can arrive as the ball does.',(24,27),{'5':(27,30),'8':(34,15)},[route('pass',(22,30),(37,50)),route('press',(48,45),(39,49))],(31,40,15,20))],fact='Marsch describes ball-focused pressure with nearby teammates supporting the first challenge.',question='Does the U.S. receiver have a useful next action before the second challenger arrives?',source=['coach'],gloss='Pressing means moving toward the ball to make an opponent hurry.'),
 dict(tab='Find the exit',title='Use the next player to find the open side.',take='The first receiver does not always need to turn. A quick return can help move the ball away from the crowd.',actors=[a('usa','CB',22,30),a('usa','GK',8,50),a('usa','6',36,42),a('usa','CB',23,72),a('usa','FB',40,91),a('can','9',28,31),a('can','MID',44,42),a('can','9',40,63),a('can','W',51,82)],states=[
 state('Invite the challenge','The centre-back passes into midfield. The receiving player checks whether turning would bring them into pressure.',(24,27),routes=[route('pass',(22,30),(36,42))]),
 state('Return, then reset','As the challenger arrives, a return pass goes back through the centre-back to the goalkeeper. This can reset possession; it does not automatically beat the press.',(38,39),{'6':(39,42)},[route('pass',(36,42),(22,30)),route('pass',(22,30),(8,50))]),
 state('Find the other side','The goalkeeper can look toward the opposite centre-back and fullback. Watch whether that fullback can receive facing upfield before a wide presser arrives.',(10,47),{'6':(39,42)},[route('pass',(8,50),(23,72)),route('pass',(23,72),(40,91))],cover=[(32,86),(48,86),(48,96),(32,96)])],fact='Marsch’s coaching account emphasizes support behind the first pressure. The illustrated passing sequence is an editorial example, not a documented move from this match.',question='Can a quick return create an outlet that has time to face forward?',source=['coach'],gloss='A switch moves play toward the other side of the pitch.'),
 dict(tab='Attack the gap',title='One player comes short. Another goes beyond.',take='A defender has a choice: follow the receiver or protect the space behind. Watch the second U.S. runner.',actors=[a('usa','MID',49,35),a('usa','9',70,45),a('usa','W',65,17),a('usa','MID',53,62),a('can','CB',76,40),a('can','CB',80,63),a('can','FB',72,13),a('can','MID',58,47),a('can','GK',94,50)],states=[
 state('Come toward the ball','The U.S. forward drops toward the passer. A wide runner stays ready to move in the other direction.',(51,32),routes=[route('run',(70,45),(62,45))]),
 state('The defender decides','If the centre-back follows, a channel can appear behind the challenge. The covering defender still matters.',(51,32),{'1':(62,45),'4':(68,43)},[route('press',(76,40),(68,43)),route('pass',(49,35),(62,45))],(74,24,13,17)),
 state('Watch the timed run','After a return pass, the passer can look into the channel. The runner is shown behind the covering defender at release; the dashed route is the possible next movement.',(51,32),{'1':(62,45),'4':(68,43),'2':(75,23)},[route('pass',(62,45),(49,35)),route('run',(75,23),(84,30)),route('pass',(49,35),(84,30))],(77,25,13,17))],fact='Marsch describes centre-backs challenging forward, with protection against the runners behind them.',question='Does the forward’s short movement create a usable route for someone else?',source=['coach'],gloss='Come short: move toward the ball. Go beyond: run into the space behind a defender.'),
 dict(tab='Cover the loss',title='Who protects the space behind the attack?',take='When a fullback advances, look behind them. A covering teammate can delay a counterattack while others recover.',actors=[a('usa','FB',62,88),a('usa','6',42,55),a('usa','CB',31,69),a('usa','CB',32,36),a('usa','GK',8,50),a('can','MID',57,58),a('can','W',50,80),a('can','9',41,43),a('can','W',61,28)],states=[
 state('Possession changes sides','Canada now have the ball with a U.S. fullback high upfield. The highlighted space is the channel to watch, not a measured danger map.',(59,55),space=(24,74,25,17)),
 state('Delay and recover','An early diagonal pass can start the counterattack. Watch the U.S. holding midfielder cover, the centre-back protect depth and the fullback begin recovering.',(59,55),{'6':(44,81)},[route('pass',(57,58),(44,81)),route('run',(44,81),(23,84)),route('run',(42,55),(36,70)),route('run',(31,69),(27,73)),route('run',(62,88),(47,86))],(24,74,25,17)),
 state('Find the protection','The first defender does not have to win the ball immediately. Watch whether the covering positions make time for teammates to get back.',(46,78),{'1':(36,70),'2':(27,73),'0':(47,86),'6':(44,81)},[route('run',(41,43),(21,51)),route('run',(61,28),(28,35))],cover=[(8,50),(27,73),(32,36)])],fact='Marsch describes early forward diagonal passes after regains. Separately, Shaffelburg scored both goals against Peru; that result does not establish where these illustrated runs began.',question='Who is already protecting the channel when possession changes?',source=['coach','peru'],gloss='Transition: the moment possession changes. Cover: protecting space behind a teammate.',person='Player to notice · Jacob Shaffelburg scored twice in the October 3 win. This role illustration is not a promise of his selection, fitness or flank.'),
 dict(tab='Press together',title='Can the U.S. make the next pass difficult?',take='A backpass can invite pressure. Watch whether the other U.S. players support the first runner.',actors=[a('can','GK',92,50),a('can','CB',78,28),a('can','CB',78,72),a('can','MID',64,48),a('can','FB',71,91),a('usa','9',72,45),a('usa','W',65,24),a('usa','W',65,73),a('usa','MID',55,53)],states=[
 state('The backpass','Canada’s centre-back returns the ball to the goalkeeper. This is a possible cue for a press, not a claim about tonight’s instructions.',(80,25),routes=[route('pass',(78,28),(92,50))]),
 state('Move together','The nearest U.S. attacker approaches the goalkeeper as teammates move toward the next options. One runner on their own is easier to pass around.',(94,47),{'5':(83,42),'6':(74,28),'7':(73,71),'8':(61,49)},[route('press',(72,45),(83,42)),route('press',(65,24),(74,28)),route('press',(65,73),(73,71)),route('press',(55,53),(61,49))]),
 state('Watch the next pass','The goalkeeper may still find midfield. Watch whether the U.S. midfielder can make that pass difficult; the illustration does not promise an interception.',(94,47),{'5':(83,42),'6':(74,28),'7':(73,71),'8':(61,49)},[route('pass',(92,50),(64,48))],(62,43,27,12))],fact='The USA–Mexico report records a Sullivan goal after pressure on the goalkeeper and a later Tillman interception and goal. These are two match events, not a team pressing rate.',question='Do the supporting players make the goalkeeper’s next option harder?',source=['mexico'],gloss='A pressing trigger is a cue to move together. A backpass is one possible example.',person='Recent match fact · Cavan Sullivan and Malik Tillman supplied those Mexico moments. The anonymous roles here are not a confirmed U.S. lineup.')]

def pitch(scene,st,uid):
 # Pitch coordinates are a teaching diagram, not recorded player locations.
 parts=[f'<svg viewBox="0 0 1050 680" role="img" aria-labelledby="{uid}-title {uid}-desc"><title id="{uid}-title">{h(scene["title"])} {h(st["title"])}</title><desc id="{uid}-desc">USA navy circles attack right. Canada red squares attack left. {h(st["copy"])} Solid lines show passes, dashes runs, dots pressure. Selected roles, not a complete lineup.</desc>',f'<defs><pattern id="{uid}-hatch" width="18" height="18" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><path d="M0 0V18" stroke="#f6c761" stroke-width="5" opacity=".65"/></pattern>']
 for kind,col in [('pass','#f9f4df'),('run','#ffd477'),('press','#ffc0b3')]:parts.append(f'<marker id="{uid}-{kind}" viewBox="0 0 12 12" refX="10" refY="6" markerWidth="3" markerHeight="3" orient="auto-start-reverse"><path d="M1 1L11 6L1 11Z" fill="{col}"/></marker>')
 parts+=['</defs><rect width="1050" height="680" fill="#173e36"/>','<g fill="#245244">'+''.join(f'<rect x="{x}" width="105" height="680"/>' for x in range(0,1050,210))+'</g>','<g fill="none" stroke="#acd0b480" stroke-width="3"><rect x="22" y="22" width="1006" height="636"/><path d="M525 22V658M22 168H177V512H22M1028 168H873V512H1028M22 262H82V418H22M1028 262H968V418H1028"/><circle cx="525" cy="340" r="91"/><path d="M2 305H22V375H2M1048 305H1028V375H1048" stroke="#e5e4c5" stroke-width="5"/></g>']
 def xy(p):return f'{p[0]*10.5:.1f},{p[1]*6.8:.1f}'
 if st['space']:
  x,y,w,hh=st['space'];parts.append(f'<rect x="{x*10.5}" y="{y*6.8}" width="{w*10.5}" height="{hh*6.8}" fill="url(#{uid}-hatch)" stroke="#ffd477" stroke-width="3" stroke-dasharray="10 8" rx="10"/>')
 if st['cover']:parts.append(f'<polygon points="{" ".join(xy(p) for p in st["cover"])}" fill="#70d9d526" stroke="#82e2d7" stroke-width="5"/>')
 for kind,points in st['routes']:
  dash={'pass':'','run':'18 12','press':'3 15'}[kind]
  # Arrowheads stop outside occupied role markers, so the direction remains visible.
  coords=[(p[0]*10.5,p[1]*6.8) for p in points]
  end=points[-1];occupied=any(abs(st['moves'].get(str(i),(actor[2],actor[3]))[0]-end[0])<.1 and abs(st['moves'].get(str(i),(actor[2],actor[3]))[1]-end[1])<.1 for i,actor in enumerate(scene['actors']))
  if occupied and len(coords)>1:
   import math
   ax,ay=coords[-2];bx,by=coords[-1];distance=math.hypot(bx-ax,by-ay);trim=min(36,distance*.55);coords[-1]=(bx-(bx-ax)*trim/distance,by-(by-ay)*trim/distance)
  path='M'+' L'.join(f'{x:.1f},{y:.1f}' for x,y in coords);col={'pass':'#f9f4df','run':'#ffd477','press':'#ffc0b3'}[kind]
  parts.append(f'<path d="{path}" fill="none" stroke="#10251d" stroke-width="10" opacity=".7"/><path d="{path}" fill="none" stroke="{col}" stroke-width="5" stroke-linecap="round" stroke-dasharray="{dash}" marker-end="url(#{uid}-{kind})"/>')
 for i,(team,role,x,y) in enumerate(scene['actors']):
  x,y=st['moves'].get(str(i),(x,y));x*=10.5;y*=6.8
  shape=f'<circle cx="{x}" cy="{y}" r="27"/>' if team=='usa' else f'<rect x="{x-27}" y="{y-27}" width="54" height="54" rx="8"/>'
  parts.append(f'<g fill="{"#122d55" if team=="usa" else "#a82b38"}" stroke="#fff2d6" stroke-width="3">{shape}</g><text x="{x}" y="{y+9}" text-anchor="middle" fill="#fff9ea" font-family="system-ui,sans-serif" font-size="{23 if len(role)>2 else 27}" font-weight="750">{role}</text>')
 bx,by=st['ball'];parts.append(f'<g transform="translate({bx*10.5} {by*6.8})"><circle r="10" fill="white" stroke="#071925" stroke-width="3"/><path d="M0-5L5-1L3 5H-3L-5-1Z" fill="#142136"/></g></svg>')
 return ''.join(parts)

def build():
 s='<section class="tactics-guide scout-section" id="duels"><p class="eyebrow">YOUR MATCH, AT A GLANCE</p><h2>See the next move.</h2><p class="scout-intro">You do not need to catch everything. Pick one question, follow it for a few minutes, and see what you notice.</p><div class="watch-three" id="three-things">'
 for i,(q,sub) in enumerate([('Can the U.S. find the free player?','Follow the receiver after the first pass.'),('Who runs into the space?','Look away from the ball for a moment.'),('Who is ready when the ball changes sides?','Find the player protecting the next move.')]):
  scene=[0,2,3][i];s+=f'<a href="#tactic-{scene}" data-pick-scene="{scene}"><span class="watch-no">0{i+1}</span><strong>{q}</strong><small>{sub} <b aria-hidden="true">↗</b></small></a>'
 s+='</div><div class="tactic-tabs" aria-label="Five things to watch">'+''.join(f'<a href="#tactic-{i}" data-scene-tab="{i}"><span>0{i+1}</span>{h(a["tab"])}</a>' for i,a in enumerate(scenes))+'</div><p class="tactic-live sr-only" role="status" aria-live="polite"></p>'
 for i,a in enumerate(scenes):
  s+=f'<article class="tactic-scene" id="tactic-{i}" aria-labelledby="tactic-title-{i}"><div class="tactic-heading"><p class="eyebrow">0{i+1} / {h(a["tab"]).upper()}</p><h3 id="tactic-title-{i}">{h(a["title"])}</h3><p>{h(a["take"])}</p></div><div class="tactic-layout"><div class="tactic-board"><p class="diagram-label">TACTICAL ILLUSTRATION · SELECTED PLAYERS · NOT A CONFIRMED LINEUP</p><div class="attack-key"><span>← CANADA ATTACK</span><span>USA ATTACK →</span></div><div class="tactic-states">'
  for j,st in enumerate(a['states']):s+=f'<figure data-tactic-state="{j}">{pitch(a,st,f"t{i}s{j}")}<figcaption><span class="state-number">{j+1} / 3 · {h(["SET UP","MOMENT","WATCH FOR"][j])}</span><h4>{h(st["title"])}</h4><p>{h(st["copy"])}</p></figcaption></figure>'
  s+='</div><div class="state-controls" hidden><button data-state-prev aria-label="Previous still">←</button><div>'+''.join(f'<button data-state-go="{j}" aria-pressed="{str(j==0).lower()}">{label}</button>' for j,label in enumerate(['Set up','Moment','Watch for']))+'</div><button data-state-next aria-label="Next still">→</button></div><p class="diagram-note">Positions and routes explain an idea; they are not tracking data or a replay.</p></div><aside class="tactic-reading"><h4>A little help reading the pitch</h4><div class="team-key"><span><i class="team-dot"></i> U.S. role</span><span><i class="team-square"></i> Canada role</span></div><ul class="line-key"><li><i class="solid"></i>Pass</li><li><i class="dashed"></i>Run</li><li><i class="dotted"></i>Pressure</li><li><i class="space"></i>Space to watch</li><li><i class="cover"></i>Cover</li></ul><details><summary>What do the letters mean?</summary><p>GK goalkeeper · CB centre-back · FB fullback · 6 holding midfielder · MID midfielder · 9 forward · W wide player.</p></details><p class="gloss">'+h(a['gloss'])+'</p><details class="tactic-evidence"><summary>Why this matters</summary><p class="eyebrow">WHAT THE SOURCES TELL US</p><p>'+h(a['fact'])+'</p><p class="eyebrow">OUR VIEWING QUESTION</p><p>'+h(a['question'])+'</p><p class="source-inline">'+' · '.join(f'<a href="{S[k][1]}">{h(S[k][0])} ↗</a>' for k in a['source'])+'</p></details>'
  if a.get('person'):s+='<p class="person-cue">'+h(a['person'])+'</p>'
  s+='<button class="all-stills" data-all-stills aria-pressed="false" hidden>Show all three stills</button></aside></div></article>'
 s+='<p class="experiment-why">Why this format: a few clear viewing questions make a match easier to follow. Three stills let you inspect the movement at your own pace, with no autoplay or forced tutorial. Print this page to keep all fifteen illustrations.</p></section>'
 return s
if __name__=='__main__':
 (root/'review/graphics/tactics-storyboard.json').write_text(json.dumps(dict(sources=S,scenes=scenes),ensure_ascii=False,indent=2)+'\n')
 (root/'review/graphics/tactics-fragment.html').write_text(build())
