from pathlib import Path
from html import escape as h
import json,re,runpy
root=Path(__file__).resolve().parents[2]
base=(root/'now.html').read_text(); header=re.search(r'<a class="skip-link".*?</header>',base).group(); footer=re.search(r'<footer.*?</footer>',base).group()
def sources(ids,data):
 return ' · '.join(f'<a href="{h(data["sources"][i]["url"],quote=True)}">{h(data["sources"][i]["label"])} ↗</a>' for i in dict.fromkeys(ids))
def shell(title,desc,body):
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101d36"><title>{h(title)} · USA 26 with Gordon</title><meta name="description" content="{h(desc,quote=True)}"><link rel="stylesheet" href="fonts-selfhosted.css"><link rel="stylesheet" href="october.css"><link rel="stylesheet" href="scout.css"><link rel="stylesheet" href="refinements.css"><script src="october.js" defer></script><script src="scout.js" defer></script></head><body class="edition scout-page">{header}<main id="main-content" tabindex="-1">{body}</main>{footer}</body></html>'
def explorer(data,heading,intro,cohorts):
 rows=[];profiles=[]
 for p in data['players']:
  name=h(p['name']);id=h(p['id']);caps=str(p.get('caps','—')); goals=str(p.get('goals','—')); cohort=p.get('cohort','camp');pos=p['position'];club=p.get('club','Not verified');analysis=p.get('analysis',{})
  rows.append(f'<a class="player-row" href="#{id}" data-position="{h(pos)}" data-cohort="{h(cohort)}" data-age="{p.get("age","")}" data-caps="{p.get("caps","")}"><span class="position">{h(pos)}</span><span><strong>{name}</strong><small>{h(club)}</small></span><span class="caps">{h(caps)}</span></a>')
  attrs={'age':p.get('age','Not asserted'),'name':p['name'],'role':p['role'],'club':club,'caps':caps,'goals':goals,'status':p['status'],'strength':analysis.get('strength','Not graded'),'question':analysis.get('question','Not graded')}
  attrs=' '.join(f'data-{k}="{h(str(v),quote=True)}"' for k,v in attrs.items())
  factcopy=''.join(f'<p>{h(f)}</p>' for f in p.get('facts',[]))
  analyst=''
  if analysis:analyst='<div class="scout-analysis"><h4>EDITORIAL VIEWING NOTES</h4><dl>'+''.join(f'<dt>{label}</dt><dd>{h(analysis[key])}</dd>' for key,label in [('strength','What the role can add'),('question','The question'),('watch','Watch for')] if key in analysis)+'</dl></div>'
  profiles.append(f'<article id="{id}" data-player {attrs} tabindex="-1"><div class="player-kicker">{h(p["status"])}</div><h3>{name}</h3><p><strong>{h(p["role"])}</strong><br><small>Role lens: editorial. Official group: {h(pos)}.</small></p><dl class="player-facts"><div><dt>Club</dt><dd>{h(club)}</dd></div><div><dt>Senior caps</dt><dd>{h(caps)}</dd></div><div><dt>Senior goals</dt><dd>{h(goals)}</dd></div></dl><p class="fact-note">{h(p.get("snapshot",data["snapshot"]))}</p>{factcopy}{analyst}<p class="source-inline">Evidence: {sources(p["sources"],data)}</p><button class="compare-trigger" data-compare="{id}" aria-pressed="false">Add to comparison</button></article>')
 options=''.join(f'<option value="{h(key)}">{h(label)}</option>' for key,label in cohorts)
 return f'<section class="scout-section" id="players" data-scout-explorer><p class="eyebrow">PLAYER NOTEBOOK</p><h2>{heading}</h2><p class="scout-intro">{intro}</p><div class="scout-tools"><label>Search name or club<input id="player-search" type="search" autocomplete="off" placeholder="Find a player"></label><label>Position<select id="player-position"><option value="all">All positions</option><option value="GK">Goalkeepers</option><option value="DEF">Defenders</option><option value="MID">Midfielders</option><option value="FWD">Forwards</option></select></label><label>Age<select id="player-age"><option value="all">All ages</option><option value="u21">Under 21</option><option value="21-25">21–25</option><option value="26+">26 and older</option></select></label><label>Senior experience<select id="player-caps"><option value="all">All experience</option><option value="0">Uncapped</option><option value="1-9">1–9 caps</option><option value="10-29">10–29 caps</option><option value="30+">30+ caps</option></select></label><label>View<select id="player-cohort">{options}</select></label></div><p class="roster-count" role="status">{len(rows)} profiles · select a name to read</p><div class="scout-layout"><div class="player-index"><div class="list-label">POSITION / PLAYER / SENIOR CAPS</div>{"".join(rows)}<p class="scout-empty" hidden>No players match. Try another name or reset the filters.</p></div><div class="player-detail">{"".join(profiles)}</div></div><section class="compare-bench" hidden aria-label="Player comparison"><h3>Two roles. Different questions.</h3><div data-compare-output aria-live="polite"></div><button class="compare-trigger" data-clear-compare>Clear comparison</button></section></section>'
def source_list(data):
 return '<section class="scout-section" id="evidence"><p class="eyebrow">FOLLOW THE EVIDENCE</p><h2>Sources & limits.</h2><details><summary>Open the dated source register</summary><ol class="scout-source-list">'+''.join(f'<li><a href="{h(s["url"],quote=True)}">{h(s["label"])} ↗</a>{" — "+h(s["note"]) if s.get("note") else ""}</li>' for s in data['sources'].values())+'</ol></details><p class="scout-status">A dated editorial notebook, not a live match feed, official selection, medical assessment or prediction of the 2030 squad. Availability can change; use the federation’s matchday release for confirmed lineups.</p></section>'
def cover(kicker,title,intro,nav):
 return f'<section class="scout-cover"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lede">{intro}</p><p class="freshness" data-freshness>Source snapshot: October 6, 2026 · Pacific time</p><nav class="scout-nav" aria-label="Notebook sections">{nav}</nav></section><div class="evidence-key"><span><b>FACT</b>Roster, status and totals from dated sources.</span><span><b>ANALYSIS</b>Our football reading and viewing questions.</span><span><b>PROJECTION</b>A watchlist, never a promised selection.</span></div>'
def lines(items):
 return '<div class="notebook-lines">'+''.join(f'<article><span class="line-no">{i+1:02}</span><div><h3>{h(item["title"])}</h3><p>{h(item["text"])}</p></div></article>' for i,item in enumerate(items))+'</div>'
if __name__=='__main__':
 data=json.loads((root/'review/next-pass/squad-data.json').read_text())
 body=cover('THE U.S. MEN · THE NEXT CYCLE','THE SQUAD.<br><em>THE HORIZON.</em>',data['intro'],'<a href="#experience">See the experience gap ↓</a><a href="#players">Explore the players ↓</a><a href="#cycle">The 2030 questions ↓</a><a href="canada.html">Canada match notebook ↗</a><a href="#evidence">Evidence ↓</a>')
 body+=f'<section class="scout-standfirst"><p>{h(data["standfirst"])}</p></section>'
 body+=runpy.run_path(str(root/'review/next-pass/build-analytics.py'))['roster_analytics'](data)
 body+=explorer(data,'Names are only<br>the beginning.',h(data['explorerIntro']),[('camp','Current camp'),('prospect','2030 watchlist'),('withdrawn','Withdrawn / unavailable'),('all','All profiles')])
 body+='<section class="scout-section" id="cycle"><p class="eyebrow">2030 · QUESTIONS, NOT CERTAINTIES</p><h2>A cycle is earned<br>one camp at a time.</h2>'+lines(data['cycle'])+'</section>'+source_list(data)
 (root/'squad.html').write_text(shell('The squad & the horizon','Explore the current USMNT camp, roles and a clearly labeled 2030 prospect watchlist.',body))
