from pathlib import Path
import json,sys
sys.path.insert(0,str(Path(__file__).resolve().parent));from importlib.machinery import SourceFileLoader
b=SourceFileLoader('scoutbuild',str(Path(__file__).with_name('build-scout.py'))).load_module();root=b.root;h=b.h
sources={
 'camp':{'label':'Canada Soccer · updated camp roster','url':'https://www.canadasoccer.com/camp/1957/mens-international-series-in-canada-and-usa/','note':'Camp participation is not an exhaustive matchday availability list.'},
 'announcement':{'label':'Canada Soccer · September/October squad announcement','url':'https://news.canadasoccer.com/canmnt-squad-named-for-september-october-international-window-following-historic-fifa-world-cup-26','note':'Club context and the World Cup sequence; later changes are reconciled below.'},
 'changes':{'label':'MLS · Caldeira and Corbeanu added','url':'https://www.mlssoccer.com/news/caldeira-corbeanu-added-to-canada-squad-for-usmnt-game','note':'Buchanan and Larin withdrew injured. The article’s Corbeanu age is not repeated.'},
 'caldeira':{'label':'Minnesota · Caldeira’s first senior call-up','url':'https://www.mnufc.com/news/forward-marcus-caldeira-called-up-to-canada-men-s-national-team-camp'},
 'caldeira-story':{'label':'Minnesota · Caldeira’s club breakthrough','url':'https://www.mnufc.com/news/storylines-marcus-caldeira-s-journey-to-major-league-success'},
 'vancouver':{'label':'Vancouver · international call-up tracker','url':'https://www.whitecapsfc.com/news/whitecaps-september-october-international-call-up-tracker','note':'Badwal returned with a hamstring strain; also documents Priso’s starts.'},
 'knight-lebel':{'label':'Motherwell · Knight-Lebel camp confirmation, Sep 22','url':'https://www.motherwellfc.co.uk/2026/09/22/jamie-knight-lebel-in-canada-squad/'},
 'chile':{'label':'Canada Soccer · Canada 1–0 Chile, Sep 26','url':'https://canadasoccer.com/match/6620/','note':'David 12′. Chile dismissals at 35′ and 49′ matter when interpreting the clean sheet.'},
 'peru':{'label':'Canada Soccer · Canada 2–0 Peru, Oct 3','url':'https://canadasoccer.com/match/6619/','note':'Shaffelburg 19′ and 35′; Jebbison assisted the first; Goodman started.'},
 'series':{'label':'Canada Soccer · window viewing notes','url':'https://news.canadasoccer.com/5-things-to-watch-during-the-september-october-fifa-international-window','note':'Previous U.S. meetings were 2–1 Canada wins in September 2024 and March 2025. Its weekday typo is not repeated.'},
 'marsch':{'label':'Jesse Marsch · a national identity','url':'https://elitesoccercoaching.net/player-and-coach-development/jesse-marsch-a-national-identity','note':'Primary coaching explanation of pressure, support, stepping centre-backs and forward transitions.'},
 'usa-preview':{'label':'U.S. Soccer · match preview, Oct 5','url':'https://www.ussoccer.com/stories/2026/10/usmnt/canada-match-st-paul-minnesota','note':'Fixture and viewing information; later Canadian squad changes take precedence for availability.'}}
entries=[
 ('Jonathan David','Atlético Madrid · loan from Juventus','FWD','Forward','Scored the winner against Chile at 12 minutes.','Movement between midfield and centre-backs can precede a second run into the box.','Does the dropping movement draw a defender before the next run?','His second movement after connecting the attack.',['announcement','chile']),
 ('Jacob Shaffelburg','LAFC','MID','Wide midfielder','Scored both goals against Peru, at 19 and 35 minutes.','A wide runner arriving beyond the ball can turn a regain into depth.','Who sees the run while the first defender is drawn toward the ball?','The far-side run after Canada wins possession.',['announcement','peru']),
 ('Stephen Eustáquio','Swansea City','MID','Central midfielder','Listed with Swansea City in the federation’s window context.','The first forward pass after a regain can exploit a defence before it resets.','Can the U.S. make him receive facing his own goal?','His body orientation and the first pass after possession changes.',['announcement']),
 ('Nathan Saliba','Villarreal','MID','Central midfielder','Started both completed matches in this window.','The second midfield connection links pressure with the next attacking action.','Who supports the first presser and protects the space behind?','The second pass and the covering position as teammates go forward.',['announcement','chile','peru']),
 ('Tani Oluwaseyi','Villarreal','FWD','Forward','A former Minnesota player, now listed at Villarreal.','Runs behind a stepping defender can stretch the first line of pressure.','Does the forward run create room for another player to receive short?','Pressure on the first U.S. pass, then the run once Canada wins it.',['announcement']),
 ('Liam Millar','Birmingham City · loan from Hull','MID','Wide midfielder','Started against Peru.','An opposite-side outlet can matter as the defence shifts toward the ball.','When should he stay wide rather than join the ball-side combination?','The outlet left behind as Canada pulls the defence across.',['announcement','peru']),
 ('Niko Sigur','Toulouse','DEF','Defender','Listed at Toulouse in the federation’s window context.','A defender advancing behind pressure can keep the team compact.','What space appears behind that advance?','His support of pressure and the U.S. option into the vacated channel.',['announcement']),
 ('Richie Laryea','Toronto FC','DEF','Defender','Listed at Toronto FC in the federation’s window context.','The timing of a wide defender’s arrival can change the attacking numbers.','Can the recovery begin before the U.S. switch reaches the far side?','His arrival into attack and his first recovery steps.',['announcement']),
 ('Luc de Fougerolles','Real Salt Lake · loan from Fulham','DEF','Defender','Started both completed window matches.','A centre-back may contest a dropping receiver before that player can turn.','Follow the forward, or preserve the space behind?','The cover accompanying his decision to step up.',['announcement','chile','peru']),
 ('Ralph Priso','Vancouver Whitecaps','DEF','Defender','Vancouver confirms his starts against Chile and Peru.','The other defender’s position determines whether a step into midfield is protected.','Who takes responsibility for the space the first challenger leaves?','The other side of the defensive step-up.',['announcement','vancouver']),
 ('Dayne St. Clair','Inter Miami','GK','Goalkeeper','Started against Chile. A former Minnesota player.','Goalkeeper involvement can create another passing option against the U.S. press.','Is the next pass prepared for the receiver, or merely away from pressure?','The goalkeeper’s starting position and first decision.',['announcement','chile']),
 ('Marcus Caldeira','Minnesota United','FWD','Forward · first senior call-up','Minnesota records five goals and three assists in 11 first-team appearances, all competitions, at its published snapshot.','The club profile identifies near-post runs, headers and poacher-style finishes.','What is his first senior job if used from the bench?','The first move across a defender before the delivery.',['caldeira','caldeira-story','changes']),
 ('Theo Corbeanu','Toronto FC','FWD','Wide attacking option · late addition','Joined the camp after the Buchanan and Larin withdrawals.','An additional wide option can change the route into the final third.','Will he supply width or play as an advanced second-line attacker?','The role Marsch actually gives him; a late call-up is not a starting prediction.',['changes','announcement'])]
players=[]
import unicodedata
for name,club,pos,role,fact,strength,question,watch,refs in entries:
 id='can-'+unicodedata.normalize('NFKD',name).encode('ascii','ignore').decode().lower().replace(' ','-');players.append({'id':id,'name':name,'position':pos,'club':club,'role':role,'cohort':'camp','status':'Opponent watch · starting XI unannounced','facts':[fact],'analysis':{'strength':strength,'question':question,'watch':watch},'sources':refs})
data={'snapshot':'Canada pregame notebook · October 6, 2026. Clubs: federation window context and later call-up releases. International caps/goals are not asserted here.','players':players,'sources':sources}
(root/'review/next-pass/canada-data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
body=b.cover('MATCH NOTEBOOK · TUESDAY, OCTOBER 6, 2026','THE NEIGHBOURS.<br><em>THE PRESSURE.</em>','Canada bring a familiar pressing identity, two clean-sheet wins and a reshuffled squad. The question: can the U.S. play through pressure while protecting its own back line?','<a href="#brief">The match ↓</a><a href="#availability">Who is available? ↓</a><a href="#duels">Three viewing duels ↓</a><a href="#players">Players to watch ↓</a>')
body+='''<section class="scout-section" id="brief"><p class="eyebrow">PREGAME · NOT A LIVE SCORE</p><h2>USA v Canada.</h2><div class="match-brief"><dl><dt>Kickoff</dt><dd>October 6 · 5 p.m. Pacific<br>7 p.m. Central / 8 p.m. Eastern</dd><dt>Venue</dt><dd>Allianz Field · St. Paul, Minnesota</dd><dt>Watch</dt><dd>TNT, truTV, HBO Max, Universo and Peacock, per U.S. Soccer.</dd><dt>Lineups</dt><dd>Unannounced in the checked sources.</dd></dl><div><p class="scout-intro">Two teams starting a new cycle. A local return for former Minnesota players. A tactical test that deserves more than the scoreline.</p><p>Canada won the previous two meetings 2–1, in September 2024 and March 2025. That history adds context; it does not predict tonight.</p><p class="source-inline">'''+b.sources(['usa-preview','series'],data)+'''</p><div data-fixture="2026-10-07T00:00:00Z"><p class="match-status">Scheduled · Oct 6</p><p class="fixture-note">This notebook has no live score feed. No result has been entered.</p></div></div></div></section>'''
body+='<section class="scout-standfirst"><p>Do not confuse camp participation with match availability. The updated roster and the withdrawal notices need to be read together.</p></section>'
items=[{'title':'The confirmed late changes','text':'Tajon Buchanan and Cyle Larin withdrew injured. Theo Corbeanu and Marcus Caldeira joined; this is Caldeira’s first senior call-up. Jeevan Badwal returned to Vancouver with a hamstring strain.'},{'title':'The updated camp page','text':'Jamie Knight-Lebel, Justin Smith and Luca Petrasso appear on the updated camp page. Knight-Lebel is a Bristol City player on loan at Motherwell. Alfie Jones and Derek Cornelius are absent from that updated list; no diagnosis is asserted here.'},{'title':'Unavailable for the window','text':'The original federation announcement listed Alphonso Davies and Maxime Crépeau as unavailable. The camp page still includes Buchanan and Larin as participants, so it cannot certify tonight’s final squad or bench.'}]
body+='<section class="scout-section" id="availability"><p class="eyebrow">SQUAD RECONCILIATION</p><h2>The names changed.<br>The labels matter.</h2>'+b.lines(items)+'<p class="source-inline">'+b.sources(['camp','changes','caldeira','vancouver','knight-lebel','announcement'],data)+'</p></section>'
body+='<section class="scout-section"><p class="eyebrow">FORM WITH CONTEXT</p><h2>Two wins.<br>Read the detail.</h2>'+b.lines([{'title':'September 26 · Canada 1–0 Chile','text':'Jonathan David scored at 12 minutes. Chile had players dismissed at 35 and 49 minutes. The result and clean sheet are facts; interpreting them without the numerical advantage would miss important context.'},{'title':'October 3 · Canada 2–0 Peru','text':'Jacob Shaffelburg scored at 19 and 35 minutes. Daniel Jebbison assisted the first goal; Owen Goodman started in goal. These details identify contributions, not a promised lineup for the U.S. match.'},{'title':'The World Cup chapter','text':'Canada drew Bosnia 1–1, beat Qatar 6–0 and lost 1–2 to Switzerland; a 1–0 win over South Africa was followed by a 0–3 round-of-16 loss to Morocco.'}])+'<p class="source-inline">'+b.sources(['chile','peru','announcement'],data)+'</p></section>'
lenses={
 'press':{'title':'Can the next U.S. receiver face forward?','body':'Canada’s first press is only the visible part. Marsch emphasizes support behind it and centre-backs contesting forward before a receiver turns. Drawing pressure helps only if the next player has a usable action.','watch':'Watch the U.S. goalkeeper, centre-backs and pivot together. Find the free player beyond the first pressure, then the protection behind the pass.','path':'M60 165 L155 93 L246 135 L360 90','x':246,'y':135},
 'transition':{'title':'Who protects the channel after the ball is lost?','body':'Marsch describes diagonal forward passes after regains and several runners attacking the box. An advancing U.S. fullback changes the covering job behind him; Shaffelburg’s run is one specific viewing cue.','watch':'Watch the far-side runner before the regain. Then find the U.S. player protecting depth while the nearest teammate confronts the ball.','path':'M240 180 L320 250 L440 225','x':320,'y':250},
 'runner':{'title':'If the defender steps out, who attacks the gap?','body':'A U.S. forward dropping short can invite a centre-back to challenge. The next runner decides whether that movement actually creates depth. This is an editorial viewing duel, not a claim about the announced XI.','watch':'Follow the second U.S. runner while the first forward receives. Check whether the covering defender can see both the ball and the run.','path':'M370 150 L305 150 M300 220 L430 180','x':370,'y':185}}
svg='''<figure class="field-notebook"><svg viewBox="0 0 500 330" role="img" aria-label="Illustrative tactical shape and passing route, not an announced lineup"><rect x="18" y="18" width="464" height="294" fill="none" stroke="#a0c8b7"/><path d="M250 18v294M18 104h62v122H18M482 104h-62v122h62" fill="none" stroke="#a0c8b7"/><circle cx="250" cy="165" r="44" fill="none" stroke="#a0c8b7"/><g fill="#f7f5ee" stroke="#101d36" stroke-width="3"><circle cx="60" cy="165" r="12"/><circle cx="155" cy="93" r="12"/><circle cx="155" cy="237" r="12"/><circle cx="246" cy="135" r="12"/><circle cx="300" cy="220" r="12"/><circle cx="370" cy="150" r="12"/><circle cx="440" cy="225" r="12"/></g><g fill="#ed3448"><circle cx="195" cy="150" r="10"/><circle cx="220" cy="200" r="10"/><circle cx="280" cy="87" r="10"/><circle cx="320" cy="250" r="10"/><circle cx="360" cy="120" r="10"/><circle cx="400" cy="185" r="10"/></g><path id="lens-path" d="M60 165 L155 93 L246 135 L360 90" fill="none" stroke="#fbd15e" stroke-width="5" stroke-dasharray="8 6"/><circle id="lens-focus" cx="246" cy="135" r="25" fill="none" stroke="#fbd15e" stroke-width="3"/></svg><figcaption>SCHEMATIC POSITIONS · WHITE: U.S. / RED: CANADA<br>Selected roles only; not tracking data, a complete formation, or a projected XI.</figcaption></figure>'''
body+='<section class="scout-section" id="duels"><p class="eyebrow">ANALYSIS · THREE VIEWING DUELS</p><h2>Watch the next<br>player, too.</h2><p class="scout-intro">Marsch’s coaching explanation supplies the principles. These match-specific questions are our inference. Choose a duel to change the illustrated route.</p><div class="match-lenses" data-match-lenses><button data-lens="press" aria-pressed="true">01 · Beat the first press</button><button data-lens="transition" aria-pressed="false">02 · Protect the channel</button><button data-lens="runner" aria-pressed="false">03 · Find the second run</button></div><div class="match-brief">'+svg+'<div class="lens-copy" id="lens-copy" aria-live="polite"><h3>'+h(lenses['press']['title'])+'</h3><p data-lens-body>'+h(lenses['press']['body'])+'</p><p><strong>Look for: </strong><span data-lens-watch>'+h(lenses['press']['watch'])+'</span></p><p class="source-inline">Coaching source: '+b.sources(['marsch'],data)+'</p></div></div><p class="experiment-why">Why this interaction: separate the first visible action from the supporting movement that makes it work. It does not predict the lineup or result.</p><script type="application/json" id="lens-data">'+json.dumps(lenses).replace('<','\\u003c')+'</script></section>'
body+='<noscript><style>.match-lenses{display:none}</style><section class="scout-section"><h2>The other viewing duels.</h2>'+b.lines([{'title':lenses[key]['title'],'text':lenses[key]['body']+' '+lenses[key]['watch']} for key in ['transition','runner']])+'</section></noscript>'
body+=b.explorer(data,'The players<br>inside the problems.','Thirteen players to watch, with dated club context and editorial role questions. This is a selected opponent notebook, not an exhaustive confirmed matchday squad. International totals are deliberately not asserted.',[('camp','Selected players to watch'),('all','All profiles')])+b.source_list(data)
page=b.shell('Canada match notebook','A sourced October 6 Canada opponent dossier: availability, form, key players and tactical viewing questions.',body)
page=page.replace('data-scout-explorer>','data-scout-explorer data-no-stats>').replace('POSITION / PLAYER / SENIOR CAPS','POSITION / PLAYER / INSPECT').replace('<span class="caps">—</span>','<span class="caps" aria-hidden="true">↗</span>').replace('<div><dt>Senior caps</dt><dd>—</dd></div><div><dt>Senior goals</dt><dd>—</dd></div>','')
page=page.replace('<rect x="18" y="18"','<defs><marker id="scout-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0 0L6 3L0 6Z" fill="#fbd15e"/></marker></defs><rect x="18" y="18"',1).replace('id="lens-path" d=','id="lens-path" marker-end="url(#scout-arrow)" d=',1)
(root/'canada.html').write_text(page)
